"""
analyze_errors.py — Automated error analysis and self-healing suggestions.

Queries the memory errors table, groups by type, uses LLM to:
  - Diagnose root causes
  - Suggest concrete fixes
  - Auto-add fix tasks to the queue
  - Generate a Markdown report

Usage:
    python analyze_errors.py               # analyze all unresolved errors
    python analyze_errors.py --all         # include resolved errors too
    python analyze_errors.py --limit 20    # cap at 20 errors
    python analyze_errors.py --no-llm      # just show the table, no LLM
"""
from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

from memory import Memory, get_memory
from llm_client import LLMClient


REPORTS_DIR = Path("reports")
REPORTS_DIR.mkdir(exist_ok=True)


def analyze(
    unresolved_only: bool = True,
    limit: int = 50,
    use_llm: bool = True,
    quiet: bool = False,
) -> dict:
    mem = get_memory()
    llm = LLMClient() if use_llm else None

    errors = mem.get_recent_errors(limit=limit, unresolved_only=unresolved_only)
    if not errors:
        msg = "No errors found in memory."
        if not quiet:
            print(msg)
        return {"total": 0, "message": msg}

    # ── Group by type ─────────────────────────────────────────────────────────
    by_type: dict[str, list[dict]] = defaultdict(list)
    for e in errors:
        by_type[e["error_type"]].append(e)

    counts = Counter({t: len(es) for t, es in by_type.items()})
    top = counts.most_common(5)

    if not quiet:
        print(f"\n[analyze_errors] {len(errors)} errors, {len(by_type)} types")
        for typ, cnt in top:
            print(f"  {cnt:>3}× {typ}")

    # ── LLM diagnosis ─────────────────────────────────────────────────────────
    analyses: list[dict] = []
    tasks_added = 0

    if llm:
        for error_type, cnt in top:
            sample = by_type[error_type][0]
            prompt = (
                f"Error type: {error_type}\n"
                f"Occurrences: {cnt}\n"
                f"Sample message: {sample.get('message','')[:200]}\n"
                f"Sample context: {sample.get('context','')[:200]}\n"
                f"Traceback: {sample.get('traceback','')[:300]}\n\n"
                f"1. Root cause (1 sentence)\n"
                f"2. Concrete fix (1-2 sentences, specific to this codebase)\n"
                f"3. Prevention strategy (1 sentence)"
            )
            if not quiet:
                print(f"\n  [LLM] Diagnosing: {error_type}…")

            diagnosis = llm.generate(
                prompt,
                max_tokens=200,
                temperature=0.3,
                system="You are a Python debugging expert. Be specific and brief.",
            )
            analyses.append({"type": error_type, "count": cnt, "diagnosis": diagnosis})

            # auto-add fix task
            fix_desc = f"Fix {error_type} errors ({cnt} occurrences): " + diagnosis.split("\n")[1][:80]
            tid = mem.add_task(fix_desc, priority=8, category="error_fix")
            tasks_added += 1

            mem.log_interaction("error_analysis", error_type, diagnosis[:200], success=True)

            if not quiet:
                print(f"  → {diagnosis.splitlines()[0][:80]}")

    # ── Write report ──────────────────────────────────────────────────────────
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = REPORTS_DIR / f"error_analysis_{ts}.md"

    lines = [
        f"# Error Analysis — {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"\n**Total errors examined:** {len(errors)}  ",
        f"**Unique types:** {len(by_type)}  ",
        f"**Unresolved only:** {unresolved_only}\n",
        "\n## Error Type Distribution\n",
        "| Type | Count |",
        "|------|-------|",
    ]
    for typ, cnt in counts.most_common():
        lines.append(f"| `{typ}` | {cnt} |")

    if analyses:
        lines.append("\n## LLM Diagnoses\n")
        for a in analyses:
            lines.append(f"### `{a['type']}` ({a['count']} occurrences)\n")
            lines.append(a["diagnosis"])
            lines.append("")

    lines.append(f"\n---\n_Generated by analyze_errors.py · Tasks added: {tasks_added}_\n")
    report_path.write_text("\n".join(lines))

    result = {
        "total_errors": len(errors),
        "unique_types": len(by_type),
        "top_types": dict(top),
        "analyses": analyses,
        "tasks_added": tasks_added,
        "report": str(report_path),
    }

    if not quiet:
        print(f"\n[analyze_errors] Report: {report_path}")
        print(f"[analyze_errors] Fix tasks queued: {tasks_added}")

    return result


if __name__ == "__main__":
    unresolved_only = "--all" not in sys.argv
    use_llm = "--no-llm" not in sys.argv
    quiet = "--quiet" in sys.argv
    limit = 50
    for i, arg in enumerate(sys.argv):
        if arg == "--limit" and i + 1 < len(sys.argv):
            limit = int(sys.argv[i + 1])
    analyze(unresolved_only=unresolved_only, limit=limit, use_llm=use_llm, quiet=quiet)
