"""Extension module: vscode-extension.

Integration or extension for external systems.

Location: integration/vscode-extension
"""

# Auto-generated by scripts/generate_missing_inits.py.
# Public exports are promoted through src/spine/module_registry.json.

__all__: list[str] = []
