"""Comprehensive pytest test suite for SNS-CORE orchestrator integration.
Generated by ChatDev (Programmer + Tester agents).
"""

import json
from unittest.mock import patch

import pytest
from src.ai.sns_core_integration import SNSCoreHelper
from src.orchestration.sns_orchestrator_adapter import SNSMetrics, SNSMode, SNSOrchestratorAdapter
from src.orchestration.unified_ai_orchestrator import (
    MultiAIOrchestrator,
    OrchestrationTask,
)


@pytest.fixture
def orchestrator():
    """Create orchestrator with SNS enabled."""
    config = {"sns_enabled": True}
    return MultiAIOrchestrator(config=config)


@pytest.fixture
def sns_helper():
    """Create SNS helper instance."""
    return SNSCoreHelper()


class TestSNSCoreHelper:
    """Unit tests for SNS-CORE helper functions."""

    def test_convert_to_sns_basic(self, sns_helper):
        """Test basic SNS conversion."""
        traditional = "Analyze the code for errors and suggest fixes"
        sns = sns_helper.convert_to_sns(traditional, pattern="flow")

        assert "→" in sns  # Flow pattern symbol
        assert len(sns) < len(traditional)  # Should be shorter

    def test_validate_sns_patterns(self, sns_helper):
        """Test SNS validation."""
        valid_sns = "analyze→errors→fixes"
        is_valid, errors = sns_helper.validate_sns(valid_sns)

        assert is_valid is True
        assert len(errors) == 0

    def test_token_comparison_accuracy(self, sns_helper):
        """Test token count comparison."""
        traditional = "Please analyze the following code for potential bugs"
        sns = "analyze→code→bugs"

        metrics = sns_helper.compare_token_counts(traditional, sns)

        assert "savings_percent" in metrics
        assert metrics["savings_percent"] > 30  # At least 30% savings

    def test_template_generation(self, sns_helper):
        """Test SNS template retrieval."""
        template = sns_helper.get_sns_template("orchestrator")

        assert template is not None
        assert isinstance(template, str)


class TestOrchestratorSNSIntegration:
    """Integration tests for orchestrator with SNS."""

    @pytest.mark.asyncio
    async def test_ollama_with_sns_enabled(self, orchestrator):
        """Test Ollama task with SNS enabled."""
        task = OrchestrationTask(
            task_id="test_sns",
            task_type="analysis",
            priority=1,
            content="Analyze code for bugs and suggest improvements",
        )

        result = await orchestrator.orchestrate_task_async(task=task, preferred_systems=["ollama"])

        assert result["status"] == "success"
        assert result["primary_result"]["sns_enabled"] is True
        assert "original_content" in result["primary_result"]

    @pytest.mark.asyncio
    async def test_ollama_with_sns_disabled(self):
        """Test Ollama task with SNS disabled."""
        config = {"sns_enabled": False}
        orchestrator = MultiAIOrchestrator(config=config)

        task = OrchestrationTask(
            task_id="test_traditional",
            task_type="analysis",
            priority=1,
            content="Analyze code",
        )

        result = await orchestrator.orchestrate_task_async(task=task, preferred_systems=["ollama"])

        assert result["primary_result"]["sns_enabled"] is False
        assert "original_content" not in result["primary_result"]

    @pytest.mark.asyncio
    async def test_chatdev_with_sns_enabled(self, orchestrator):
        """Test ChatDev task with SNS enabled."""
        task = OrchestrationTask(
            task_id="test_chatdev_sns",
            task_type="code_generation",
            priority=1,
            content="Generate test suite for module X",
        )

        result = await orchestrator.orchestrate_task_async(task=task, preferred_systems=["chatdev"])

        assert result["status"] == "success"
        assert result["primary_result"]["sns_enabled"] is True


class TestSNSABTesting:
    """A/B tests comparing traditional vs SNS notation."""

    @pytest.mark.parametrize(
        "prompt,expected_savings",
        [
            ("Analyze code for errors", 35),
            ("Generate comprehensive test suite with fixtures", 40),
            ("Review code and suggest architectural improvements", 45),
        ],
    )
    def test_token_savings_range(self, sns_helper, prompt, expected_savings):
        """Test token savings meet 35-50% target."""
        sns = sns_helper.convert_to_sns(prompt)
        metrics = sns_helper.compare_token_counts(prompt, sns)

        assert metrics["savings_percent"] >= expected_savings
        assert metrics["savings_percent"] <= 55  # Allow slight variation

    def test_semantic_equivalence(self, sns_helper):
        """Test that SNS maintains semantic meaning."""
        traditional = "Review the code and identify potential security vulnerabilities"
        sns = sns_helper.convert_to_sns(traditional, pattern="flow")

        # Both should contain key concepts
        assert any(word in sns.lower() for word in ["review", "code", "security", "vuln"])


class TestSNSErrorHandling:
    """Test error handling and fallback behavior."""

    @pytest.mark.asyncio
    async def test_sns_conversion_failure_fallback(self):
        """Test fallback to traditional on SNS failure."""
        config = {"sns_enabled": True}
        orchestrator = MultiAIOrchestrator(config=config)

        task = OrchestrationTask(
            task_id="test_fallback",
            task_type="analysis",
            priority=1,
            content="Test" * 1000,  # Deliberately problematic
        )

        with patch("src.ai.sns_core_integration.SNSCoreHelper.convert_to_sns") as mock:
            mock.side_effect = Exception("Conversion failed")

            result = await orchestrator.orchestrate_task_async(
                task=task, preferred_systems=["ollama"]
            )

            assert result["status"] == "success"  # Should still succeed

    def test_invalid_sns_validation(self, sns_helper):
        """Test validation catches invalid SNS."""
        invalid_sns = "not valid sns at all!!!"
        is_valid, errors = sns_helper.validate_sns(invalid_sns)

        assert is_valid is False
        assert len(errors) > 0


class TestSNSOrchestratorAdapter:
    """Unit tests for SNSOrchestratorAdapter token metrics behavior."""

    @pytest.mark.asyncio
    async def test_execute_task_with_sns_tracks_metrics(self, monkeypatch):
        """SNS mode should track token metrics for completed tasks."""
        adapter = SNSOrchestratorAdapter(sns_mode=SNSMode.ENABLED)

        async def fake_orchestrate_task_async(*, task):
            return {"primary_result": {"task_id": task.task_id, "ok": True}}

        monkeypatch.setattr(adapter, "orchestrate_task_async", fake_orchestrate_task_async)
        monkeypatch.setattr(adapter, "_convert_to_sns", lambda _task: "analyze→code→bugs")
        monkeypatch.setattr(adapter.sns_helper, "validate_sns", lambda _prompt: (True, []))
        monkeypatch.setattr(
            adapter.sns_helper,
            "compare_token_counts",
            lambda _traditional, _sns: {
                "traditional_tokens": 100,
                "sns_tokens": 45,
                "tokens_saved": 55,
                "savings_percent": 55.0,
                "compression_ratio": 2.22,
            },
        )

        result = await adapter.execute_task_sns(
            "Analyze this code for bugs and suggest fixes", task_type="analysis"
        )

        assert result["mode"] == "sns_core"
        assert len(adapter.sns_metrics) == 1
        metric = next(iter(adapter.sns_metrics.values()))
        assert metric.tokens_saved == 55
        assert adapter.total_tokens_saved == 55

    def test_get_sns_metrics_summary_aggregates_totals(self):
        """Summary should aggregate tokens across tracked tasks."""
        adapter = SNSOrchestratorAdapter(sns_mode=SNSMode.ENABLED)
        adapter.sns_metrics = {
            "task-1": SNSMetrics(
                task_id="task-1",
                traditional_tokens=120,
                sns_tokens=60,
                tokens_saved=60,
                savings_percent=50.0,
                compression_ratio=2.0,
            ),
            "task-2": SNSMetrics(
                task_id="task-2",
                traditional_tokens=80,
                sns_tokens=40,
                tokens_saved=40,
                savings_percent=50.0,
                compression_ratio=2.0,
            ),
        }

        summary = adapter.get_sns_metrics_summary()
        assert summary["total_tasks"] == 2
        assert summary["total_traditional_tokens"] == 200
        assert summary["total_sns_tokens"] == 100
        assert summary["total_tokens_saved"] == 100

    def test_export_sns_metrics_writes_json(self, tmp_path):
        """Export should persist summary and task metrics payload."""
        adapter = SNSOrchestratorAdapter(sns_mode=SNSMode.ENABLED)
        adapter.sns_metrics = {
            "task-1": SNSMetrics(
                task_id="task-1",
                traditional_tokens=50,
                sns_tokens=25,
                tokens_saved=25,
                savings_percent=50.0,
                compression_ratio=2.0,
            )
        }

        output = tmp_path / "sns_metrics.json"
        assert adapter.export_sns_metrics(output) is True
        data = json.loads(output.read_text(encoding="utf-8"))
        assert data["summary"]["total_tasks"] == 1
        assert data["tasks"][0]["task_id"] == "task-1"


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--cov=src.orchestration", "--cov=src.ai"])
