#!/usr/bin/env tsx
/**
 * Walk the repo, identify READMEs, ADRs, TODOs, tutorial fragments,
 * and produce /docs/README.md, /docs/FAQ.md, /docs/ROADMAP.md, /docs/TUTORIAL.md.
 */
import { readdirSync, statSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const docsDir = join(root, "docs");

// Ensure docs directory exists
if (!existsSync(docsDir)) {
  mkdirSync(docsDir, { recursive: true });
}

const out = (f: string, s: string) => writeFileSync(join(docsDir, f), s, "utf8");

function walk(dir: string, acc: string[] = []): string[] {
  try {
    for (const file of readdirSync(dir)) {
      if (file.startsWith(".git") || file.startsWith("node_modules")) continue;
      const p = join(dir, file);
      const st = statSync(p);
      if (st.isDirectory()) {
        walk(p, acc);
      } else if (/\.(md|mdx|rtf|txt)$/i.test(file)) {
        acc.push(p);
      }
    }
  } catch (error) {
    console.warn(`[DOCS] Failed to walk ${dir}:`, error);
  }
  return acc;
}

function safeRead(p: string): string {
  try {
    const content = readFileSync(p, "utf8");
    // Truncate very long files
    return content.length > 12000 ? content.slice(0, 12000) + "\n\n[...truncated...]" : content;
  } catch {
    return "*unreadable*";
  }
}

function collect() {
  console.log("[DOCS] Scanning repository for documentation...");
  
  const files = walk(root);
  const readmes = files.filter(f => /readme\.md$/i.test(f));
  const adrs = files.filter(f => /adr/i.test(f) || /decision/i.test(f));
  const todos = files.filter(f => /todo/i.test(f) || /roadmap/i.test(f));
  const tutorials = files.filter(f => /tutorial|guide|howto/i.test(f));
  const configs = files.filter(f => /config|setup|install/i.test(f));
  
  console.log(`[DOCS] Found ${files.length} total files: ${readmes.length} READMEs, ${adrs.length} ADRs, ${todos.length} todos, ${tutorials.length} tutorials`);

  const hdr = (t: string) => `\n\n---\n## ${t}\n`;
  const section = (name: string, arr: string[]) =>
    hdr(name) + arr.map(p => `\n### ${p.replace(root + "/", "")}\n\n` + safeRead(p)).join("");

  // Main unified documentation
  const mainDoc = `# CoreLink Foundation / ΞNuSyQ – Unified Documentation

*Generated by \`scripts/generate-docs.ts\` on ${new Date().toISOString()}*

This document aggregates scattered documentation across the repository into a single source of truth.
Edit source files and re-run \`npm run docs:gen\` to refresh.

## System Overview

CoreLink Foundation is an autonomous development ecosystem featuring:
- **Infrastructure-First Principles**: Single-port, fail-safe, budget-aware processing
- **ZETA Autonomous Task Generation**: Parametric patterns generating hundreds of tasks
- **SimAPI**: Agent-game interaction layer for autonomous play
- **ML Nursery**: Real, lightweight ML scaffolding (Markov chains, bandits, eval harness)
- **Culture-Ship Aesthetic**: Quantum-layered development with ΞNuSyQ consciousness integration

${section("Project READMEs", readmes)}
${section("Architecture Decision Records", adrs)}
${section("Configuration & Setup", configs)}
${section("TODOs & Roadmaps", todos)}
${section("Tutorials & Guides", tutorials)}

## Auto-Generated Sections

### API Endpoints
- \`GET /readyz\` - System readiness check
- \`GET /api/health\` - Comprehensive health monitoring
- \`GET /api/sim/observe\` - Game state observation
- \`POST /api/sim/act\` - Apply action to game
- \`GET /api/hints\` - AI-powered improvement suggestions
- \`POST /api/ops/queue\` - Queue autonomous tasks
- \`GET /api/zeta/patterns\` - ZETA expansion patterns

### Key Directories
- \`agents/\` - ChatDev profiles and agent coordination
- \`ml/nursery/\` - ML scaffolding and datasets
- \`server/services/\` - Core system services
- \`client/src/state/\` - Game state management
- \`scripts/\` - Automation and generation tools

---
*Infrastructure-First Principles • Culture-Ship Aesthetic • Autonomous Development*
`;

  // FAQ from common patterns
  const faq = `# Frequently Asked Questions

*Auto-generated from codebase patterns and documentation*

## General Questions

**Q: What is CoreLink Foundation?**
A: An autonomous development ecosystem that combines incremental game mechanics with infrastructure-first development principles. It features AI agents, autonomous task generation, and a self-improving development loop.

**Q: Why combine a game with development infrastructure?**
A: The incremental/idle game mechanics drive the autonomous development process. As the game progresses, it unlocks new development capabilities, creates training data for ML models, and generates tasks for the development queue.

**Q: Can AI agents play the game?**
A: Yes! The SimAPI (\`/api/sim/*\`) allows agents to observe game state and take actions. Agents can play manually or the game can run in autopilot mode with agent decision-making.

## Technical Questions

**Q: How does the ZETA task generation work?**
A: ZETA patterns are parametric templates that expand into hundreds of concrete tasks. Post a MacroPU to the queue and it automatically expands (e.g., one macro with count:100 becomes 100 individual tasks).

**Q: What is Infrastructure-First?**
A: A design philosophy prioritizing system stability, single-port deployment, graceful degradation, and budget-aware processing. The system never crashes - it degrades safely when resources are constrained.

**Q: How does the ML nursery work?**
A: It provides lightweight ML scaffolding including Markov chains for text generation, bandit algorithms for optimization, and evaluation harnesses. All designed to run on free-tier Replit instances.

**Q: What are [Msg⛛{X}] tags?**
A: Symbolic message protocol for tracking recursive operations and autonomous coordination. Each major system event gets tagged for monitoring and ML training data collection.

## Development Questions

**Q: How do I add new game features?**
A: Update the game state reducer in \`client/src/state/game.ts\`, add corresponding actions to the SimAPI, and create test cases for agent interaction.

**Q: How do I create new autonomous tasks?**
A: Either add individual PUs to the queue via \`POST /api/ops/queue\` or create MacroPUs that expand into many tasks automatically.

**Q: How do I debug system issues?**
A: Check \`/readyz\` for system status, \`/api/health\` for detailed diagnostics, and \`/api/hints\` for AI-suggested improvements.

---
Last updated: ${new Date().toISOString()}
`;

  // Roadmap synthesis
  const roadmap = `# Development Roadmap

*Synthesized from scattered TODOs and planning documents*

## Current Phase: Infrastructure Completion

### ✅ Completed
- Single-port server architecture
- ZETA autonomous task generation
- SimAPI for agent-game interaction
- Basic game state management
- Error boundaries and graceful degradation
- ML nursery scaffolding

### 🔄 In Progress
- MacroPU expansion system
- Documentation generation pipeline
- Autoplay and agent coordination
- Budget-aware task processing

### 📋 Planned

#### Phase 1: Game Engine Completion
- Resource management systems
- Research and upgrade trees
- Procedural content generation
- Save/load functionality
- Performance optimization

#### Phase 2: Agent Intelligence
- Advanced decision-making algorithms
- Multi-agent coordination
- Learning from gameplay data
- Autonomous refactoring capabilities

#### Phase 3: ML Enhancement
- Improved text generation models
- Predictive task prioritization
- Adaptive difficulty balancing
- Real-time optimization suggestions

#### Phase 4: User Experience
- Accessibility improvements
- Mobile-friendly interface
- Tutorial and onboarding
- Community features

#### Phase 5: Advanced Features
- Cross-universe diplomacy mechanics
- Consciousness integration frameworks
- Quantum interface development
- Advanced visualization systems

---
*Updated automatically by documentation generator*
`;

  // Tutorial guide
  const tutorial = `# Getting Started Tutorial

## Quick Start (Zero to Play in 5 minutes)

### 1. System Check
\`\`\`bash
# Verify system is ready
curl localhost:5000/readyz

# Should return: {"ready": true, "checkpoint": "operational"}
\`\`\`

### 2. Start the Game
1. Open the application in your browser
2. Click "New Game" on the main menu
3. Watch the state transition: main_menu → new_game → loading → playing

### 3. Enable Autopilot
\`\`\`bash
# Via API
curl -X POST localhost:5000/api/sim/act \\
  -H "Content-Type: application/json" \\
  -d '{"actor":"human:tutorial","action":"autopilot","payload":{}}'

# Or click "Enable Autopilot" in the UI
\`\`\`

### 4. Observe Autonomous Play
\`\`\`bash
# Watch game state
curl localhost:5000/api/sim/observe

# Monitor rewards
curl localhost:5000/api/sim/reward
\`\`\`

## Agent Development Tutorial

### Creating Your First Agent
\`\`\`javascript
// Simple agent that buys materials when energy is high
async function agentDecision(gameState) {
  if (gameState.resources.energy > 80) {
    return { action: "buy", payload: { item: "materials" } };
  }
  return { action: "tick", payload: {} };
}

// Connect to game
const response = await fetch('/api/sim/act', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    actor: 'agent:my-bot',
    action: 'buy',
    payload: { item: 'materials' }
  })
});
\`\`\`

### Queuing Autonomous Tasks
\`\`\`bash
# Queue individual tasks
curl -X POST localhost:5000/api/ops/queue \\
  -H "Content-Type: application/json" \\
  -d '[{"type":"DocPU","title":"Write agent tutorial","priority":"high"}]'

# Queue macro that expands to many tasks
curl -X POST localhost:5000/api/ops/queue \\
  -H "Content-Type: application/json" \\
  -d '[{"type":"MacroPU","id":"TUTORIAL","category":"docs","template":{"type":"DocPU","title":"Tutorial step number i","estTokens":10,"priority":"medium"},"expand":{"count":5}}]'
\`\`\`

## Advanced Usage

### Documentation Generation
\`\`\`bash
npm run docs:gen
# Generates unified docs from scattered files
\`\`\`

### ML Nursery Operations
\`\`\`bash
# Curate training data
npm run ml:curate

# Run toy evaluations
npm run ml:eval
\`\`\`

### System Administration
\`\`\`bash
# Health check
curl localhost:5000/api/health

# Get improvement hints
curl localhost:5000/api/hints

# Activate system seal
curl -X POST localhost:5000/api/ops/reindex
\`\`\`

---
*Infrastructure-First • Agent-Driven • Autonomously Generated*
`;

  // Write all documentation files
  out("README.md", mainDoc);
  out("FAQ.md", faq);
  out("ROADMAP.md", roadmap);
  out("TUTORIAL.md", tutorial);
  
  console.log("[DOCS] ✅ Generated documentation files:");
  console.log("  - docs/README.md");
  console.log("  - docs/FAQ.md");
  console.log("  - docs/ROADMAP.md");
  console.log("  - docs/TUTORIAL.md");
}

// CLI execution
if (import.meta.url === `file://${process.argv[1]}`) {
  collect();
}