#!/usr/bin/env python3
"""Live Terminal Routing Activation.

This script activates LIVE terminal routing by:
1. Setting up output monitoring
2. Creating PowerShell scripts for each terminal to tail their logs
3. Generating VSCode tasks to launch terminal watchers
4. Integrating with existing ecosystem

This makes your terminals ACTUALLY USEFUL by showing live output!
"""

import argparse
import json
from datetime import datetime
from pathlib import Path

CANONICAL_TERMINAL_NAMES = [
    "claude",
    "copilot",
    "codex",
    "chatdev",
    "ai_council",
    "intermediary",
    "errors",
    "suggestions",
    "tasks",
    "tests",
    "zeta",
    "agents",
    "metrics",
    "anomalies",
    "future",
    "main",
    "culture_ship",
    "moderator",
    "system",
    "chatgpt_bridge",
    "simulatedverse",
    "ollama",
    "lmstudio",
    "powershell_extension",
    "pwsh",
]

AGENT_TERMINAL_NAMES = [
    "claude",
    "copilot",
    "codex",
    "chatdev",
    "ai_council",
    "intermediary",
]

TERMINAL_LABEL_OVERRIDES = {
    "ai_council": "AI Council",
    "chatdev": "ChatDev",
    "chatgpt_bridge": "ChatGPT Bridge",
    "lmstudio": "LM Studio",
    "powershell_extension": "PowerShell Extension",
    "pwsh": "pwsh",
    "simulatedverse": "SimulatedVerse",
}

LOG_FILE_ALIASES = {
    # Historical file naming aliases from previous terminal generations
    "lmstudio": ["lm_studio.log"],
    "simulatedverse": ["simulated_verse.log"],
}


def _to_windows_path(path: Path) -> str:
    path_str = str(path)
    if path_str.startswith("/mnt/") and len(path_str) > 6:
        drive = path_str[5].upper()
        tail = path_str[7:].replace("/", "\\")
        return f"{drive}:\\{tail}"
    return path_str


def generate_terminal_watcher_ps1(terminal_name: str, log_file: Path, output_dir: Path) -> Path:
    """Generate PowerShell script that watches a terminal log file."""
    log_file_name = log_file.name
    fallback_aliases = LOG_FILE_ALIASES.get(terminal_name, [])
    if fallback_aliases:
        fallback_literal = ",\n    ".join(f'(Join-Path $logDir "{alias_name}")' for alias_name in fallback_aliases)
        fallback_block = f"@(\n    {fallback_literal}\n)"
    else:
        fallback_block = "@()"
    ps1_content = f"""# Terminal Watcher for {terminal_name}
# Auto-generated by activate_live_terminal_routing.py

$repoRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$logDir = Join-Path $repoRoot "data\\terminal_logs"
$primaryLogFile = Join-Path $logDir "{log_file_name}"
$terminalName = "{terminal_name}"
$sourceLog = $primaryLogFile
$sourceLabel = "NuSyQ terminal log"
$fallbackLogs = {fallback_block}

if ($terminalName -eq "copilot") {{
    $logsRoot = Join-Path $env:APPDATA "Code\\logs"
    if (Test-Path $logsRoot) {{
        $copilotCandidates = Get-ChildItem -Path $logsRoot -Filter "GitHub Copilot Chat.log" -Recurse -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending
        if ($copilotCandidates) {{
            $sourceLog = $copilotCandidates[0].FullName
            $sourceLabel = "VS Code Copilot Chat log"
        }}
    }}
}}

if (($sourceLog -eq $primaryLogFile) -and (!(Test-Path $sourceLog))) {{
    foreach ($fallback in $fallbackLogs) {{
        if (![string]::IsNullOrWhiteSpace($fallback) -and (Test-Path $fallback)) {{
            $sourceLog = $fallback
            $sourceLabel = "NuSyQ legacy terminal log"
            break
        }}
    }}
}}

Write-Host "=== $terminalName Terminal - Live Output ===" -ForegroundColor Cyan
Write-Host "Source: $sourceLabel" -ForegroundColor Gray
Write-Host "Watching: $sourceLog" -ForegroundColor Gray
if ($sourceLog -ne $primaryLogFile) {{
    Write-Host "Mirror destination: $primaryLogFile" -ForegroundColor DarkGray
}}
Write-Host ""

# Ensure destination log exists
if (!(Test-Path $primaryLogFile)) {{
    New-Item -ItemType File -Path $primaryLogFile -Force | Out-Null
    Write-Host "Created log file: $primaryLogFile" -ForegroundColor Yellow
}}

if (!(Test-Path $sourceLog)) {{
    Write-Host "Source log not found: $sourceLog" -ForegroundColor Red
    Write-Host "Tip: open VS Code Copilot chat once, then relaunch this watcher." -ForegroundColor Yellow
    exit 1
}}

# Tail the log file and format output
Get-Content $sourceLog -Wait -Tail 20 | ForEach-Object {{
    $line = $_
    if ($null -eq $line) {{
        return
    }}

    $trimmed = $line.Trim()
    if ($trimmed.Length -eq 0) {{
        return
    }}

    $entry = $null
    if ($trimmed.StartsWith("{{") -and $trimmed.EndsWith("}}")) {{
        try {{
            $entry = $trimmed | ConvertFrom-Json -ErrorAction Stop
        }} catch {{
            $entry = $null
        }}
    }}

        if ($null -ne $entry) {{
        $timestamp = $entry.timestamp
        $level = $entry.level
        $message = $entry.message
        if ($null -ne $message) {{
            $message = "$message"
            $message = ($message -replace '[^\\x00-\\x7F]', '?')
        }}

        # Color based on level
        $color = switch ($level) {{
            "ERROR" {{ "Red" }}
            "WARNING" {{ "Yellow" }}
            "INFO" {{ "White" }}
            "DEBUG" {{ "Gray" }}
            default {{ "White" }}
        }}

        Write-Host "[$timestamp] " -NoNewline -ForegroundColor Gray
        Write-Host "[$level] " -NoNewline -ForegroundColor $color
        Write-Host $message -ForegroundColor $color

        if ($sourceLog -ne $primaryLogFile) {{
            Add-Content -Path $primaryLogFile -Value $trimmed -Encoding UTF8 -ErrorAction SilentlyContinue
        }}
    }} else {{
        # If not JSON, print as plain text but mirror as NDJSON for tooling.
        $safeLine = ($line -replace '[^\\x00-\\x7F]', '?')
        Write-Host $safeLine -ForegroundColor White
        if ($sourceLog -ne $primaryLogFile) {{
            $mirrorEntry = @{{
                timestamp = (Get-Date).ToString("o")
                level = "INFO"
                source = $terminalName
                message = $safeLine
            }} | ConvertTo-Json -Compress
            Add-Content -Path $primaryLogFile -Value $mirrorEntry -Encoding UTF8 -ErrorAction SilentlyContinue
        }}
    }}
}}
"""

    ps1_file = output_dir / f"watch_{terminal_name}_terminal.ps1"
    ps1_file.write_text(ps1_content, encoding="utf-8")
    return ps1_file


def load_terminal_names(root: Path) -> list[str]:
    """Load terminal names from data/terminal_routing.json when available."""
    configured_names: list[str] = []
    config_path = root / "data" / "terminal_routing.json"
    if config_path.exists():
        try:
            data = json.loads(config_path.read_text(encoding="utf-8"))
            terminals = data.get("terminals", {})
            if isinstance(terminals, dict) and terminals:
                configured_names = list(terminals.keys())
        except (OSError, json.JSONDecodeError):
            pass

    merged: list[str] = []
    for terminal_name in configured_names + CANONICAL_TERMINAL_NAMES:
        if terminal_name not in merged:
            merged.append(terminal_name)
    return merged


def _terminal_label(terminal_name: str) -> str:
    return TERMINAL_LABEL_OVERRIDES.get(terminal_name, terminal_name.replace("_", " ").title())


def generate_vscode_tasks(terminal_names: list[str], output_dir: Path) -> dict:
    """Generate VSCode tasks.json for terminal watchers."""
    tasks = {
        "version": "2.0.0",
        "tasks": [],
    }

    # Create a task for each terminal watcher
    for terminal_name in terminal_names:
        ps1_file = output_dir / f"watch_{terminal_name}_terminal.ps1"
        ps1_cmd_path = _to_windows_path(ps1_file)
        label = _terminal_label(terminal_name)
        task = {
            "label": f"Watch {label} Terminal",
            "type": "shell",
            "command": f'powershell -NoProfile -ExecutionPolicy Bypass -NoExit -File "{ps1_cmd_path}"',
            "presentation": {
                "echo": True,
                "reveal": "always",
                "focus": False,
                "panel": "dedicated",
                "showReuseMessage": False,
                "clear": False,
            },
            "problemMatcher": [],
            "isBackground": True,
        }
        tasks["tasks"].append(task)

    agent_task_labels = [
        f"Watch {_terminal_label(name)} Terminal" for name in terminal_names if name in AGENT_TERMINAL_NAMES
    ]
    operational_task_labels = [
        f"Watch {_terminal_label(name)} Terminal" for name in terminal_names if name not in AGENT_TERMINAL_NAMES
    ]

    # Add master task to launch all watchers
    tasks["tasks"].append(
        {
            "label": "Watch All Agent Terminals",
            "dependsOn": agent_task_labels,
            "dependsOrder": "parallel",
            "problemMatcher": [],
        }
    )

    tasks["tasks"].append(
        {
            "label": "Watch All Operational Terminals",
            "dependsOn": operational_task_labels,
            "dependsOrder": "parallel",
            "problemMatcher": [],
        }
    )

    tasks["tasks"].append(
        {
            "label": "Watch ALL Terminals (Full System)",
            "dependsOn": [f"Watch {_terminal_label(t)} Terminal" for t in terminal_names],
            "dependsOrder": "parallel",
            "problemMatcher": [],
        }
    )

    return tasks


def generate_master_terminal_launcher(terminal_names: list[str]) -> str:
    """Generate master script to launch all terminal watchers."""
    watchers_literal = ",\n".join(f'    "watch_{terminal_name}_terminal.ps1"' for terminal_name in terminal_names)
    script = f"""#!/usr/bin/env python3
\"\"\"
Master Terminal Launcher - Starts all terminal watchers

Run this to see live output from all agents and operational terminals!
\"\"\"

import os
import shutil
import subprocess
import time
from pathlib import Path

WATCHERS = [
{watchers_literal}
]

def _to_windows_path(path: Path) -> str:
    path_str = str(path)
    if path_str.startswith("/mnt/") and len(path_str) > 6:
        drive = path_str[5].upper()
        tail = path_str[7:].replace("/", "\\\\")
        return f"{{drive}}:\\\\{{tail}}"
    return path_str

def main():
    root = Path(__file__).parent.parent
    watcher_dir = root / "data" / "terminal_watchers"
    shell = shutil.which("pwsh") or shutil.which("powershell")
    if not shell:
        print("❌ PowerShell executable not found (pwsh/powershell).")
        return 1

    print("🚀 Launching Terminal Watchers...")
    print("=" * 70)
    print(f"Watcher Dir: {{watcher_dir}}")
    print(f"Shell: {{shell}}")

    processes = []
    for watcher in WATCHERS:
        watcher_path = watcher_dir / watcher
        if not watcher_path.exists():
            print(f"⚠️  Watcher not found: {{watcher}}")
            continue

        terminal_name = watcher.replace("watch_", "").replace("_terminal.ps1", "")
        print(f"   Launching {{terminal_name}} watcher...")

        # Launch in new PowerShell window
        args = [shell, "-NoExit"]
        if os.path.basename(shell).lower().startswith("powershell"):
            args.extend(["-ExecutionPolicy", "Bypass"])
        args.extend(["-File", _to_windows_path(watcher_path)])
        creation_flags = 0
        if os.name == "nt" and hasattr(subprocess, "CREATE_NEW_CONSOLE"):
            creation_flags = subprocess.CREATE_NEW_CONSOLE
        proc = subprocess.Popen(
            args,
            creationflags=creation_flags
        )
        processes.append(proc)
        time.sleep(0.5)  # Stagger launches

    print(f"\\n✅ Launched {{len(processes)}} terminal watchers!")
    print("   Each terminal is now showing live output")
    print("   Press Ctrl+C to stop monitoring")

    try:
        # Keep script running
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\\n🛑 Stopping terminal watchers...")
        for proc in processes:
            proc.terminate()
        print("✅ All watchers stopped")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
"""
    return script


def validate_terminal_routing(root: Path) -> int:
    """Validate terminal routing configuration and generated artifacts."""
    terminal_names = load_terminal_names(root)
    issues: list[str] = []
    warnings: list[str] = []

    routing_path = root / "data" / "terminal_routing.json"
    if not routing_path.exists():
        issues.append("Missing data/terminal_routing.json")

    log_dir = root / "data" / "terminal_logs"
    watcher_dir = root / "data" / "terminal_watchers"
    tasks_path = root / ".vscode" / "terminal_watcher_tasks.json"

    if not log_dir.exists():
        issues.append("Missing data/terminal_logs directory")
    if not watcher_dir.exists():
        issues.append("Missing data/terminal_watchers directory")

    for terminal_name in terminal_names:
        log_file = log_dir / f"{terminal_name}.log"
        watcher_file = watcher_dir / f"watch_{terminal_name}_terminal.ps1"
        if not log_file.exists():
            alias_paths = [log_dir / alias_name for alias_name in LOG_FILE_ALIASES.get(terminal_name, [])]
            if not any(path.exists() for path in alias_paths):
                warnings.append(f"Missing log file (created on first write): {log_file}")
        if not watcher_file.exists():
            issues.append(f"Missing watcher script: {watcher_file}")
        else:
            content = watcher_file.read_text(encoding="utf-8")
            normalized = content.replace("/", "\\")
            expected_names = [f"{terminal_name}.log", *LOG_FILE_ALIASES.get(terminal_name, [])]
            if "terminal_logs" not in normalized:
                issues.append(f"Watcher missing terminal_logs reference: {watcher_file}")
            elif not any(f'"{name}"' in content for name in expected_names):
                issues.append(f"Watcher log path mismatch for {terminal_name}: {watcher_file}")

    if tasks_path.exists():
        try:
            tasks = json.loads(tasks_path.read_text(encoding="utf-8"))
            task_labels = {task.get("label", "") for task in tasks.get("tasks", []) if isinstance(task, dict)}
            for terminal_name in terminal_names:
                expected_label = f"Watch {_terminal_label(terminal_name)} Terminal"
                if expected_label not in task_labels:
                    issues.append(f"Missing task: {expected_label}")
        except (OSError, json.JSONDecodeError):
            issues.append("Failed to parse .vscode/terminal_watcher_tasks.json")
    else:
        issues.append("Missing .vscode/terminal_watcher_tasks.json")

    if warnings:
        print("⚠️  Terminal routing validation warnings:")
        for warning in warnings:
            print(f"   - {warning}")

    if issues:
        print("❌ Terminal routing validation failed:")
        for issue in issues:
            print(f"   - {issue}")
        return 1

    print("✅ Terminal routing validation passed.")
    return 0


def main():
    """Set up live terminal routing system."""
    root = Path(__file__).parent.parent
    output_dir = root / "data" / "terminal_logs"
    watcher_dir = root / "data" / "terminal_watchers"
    watcher_dir.mkdir(parents=True, exist_ok=True)

    print("🔧 Setting Up Live Terminal Routing")
    print("=" * 70)

    # Terminal names from config
    terminal_names = load_terminal_names(root)

    # Generate PowerShell watchers for each terminal
    print("\n📝 Generating Terminal Watchers...")
    generated_watchers = []
    for terminal_name in terminal_names:
        log_file = output_dir / f"{terminal_name}.log"
        ps1_file = generate_terminal_watcher_ps1(terminal_name, log_file, watcher_dir)
        generated_watchers.append(ps1_file)
        print(f"   ✓ {terminal_name} watcher: {ps1_file.name}")

    # Generate VSCode tasks
    print("\n📝 Generating VSCode Tasks...")
    tasks = generate_vscode_tasks(terminal_names, watcher_dir)
    tasks_file = root / ".vscode" / "terminal_watcher_tasks.json"
    tasks_file.write_text(json.dumps(tasks, indent=2), encoding="utf-8")
    print(f"   ✓ Tasks file: {tasks_file}")

    # Generate master launcher
    print("\n📝 Generating Master Launcher...")
    launcher_script = generate_master_terminal_launcher(terminal_names)
    launcher_file = root / "scripts" / "launch_all_terminal_watchers.py"
    launcher_file.write_text(launcher_script, encoding="utf-8")
    print(f"   ✓ Launcher: {launcher_file}")

    # Generate quick reference guide
    print("\n📝 Generating Quick Reference...")
    quick_ref = f"""# Live Terminal Routing - Quick Reference

Generated: {datetime.now().isoformat()}

## What This Does

Your terminals are now configured for LIVE OUTPUT ROUTING! Instead of just showing
static banners, they will display actual real-time output from agents and systems.

## How to Use

### Option 1: VSCode Tasks (Recommended)
1. Press `Ctrl+Shift+P` in VSCode
2. Type "Tasks: Run Task"
3. Select one of:
   - "Watch All Agent Terminals" - Claude, Copilot, Codex, ChatDev, Council, Intermediary
   - "Watch All Operational Terminals" - Errors, Suggestions, Tasks, Metrics, etc.
   - "Watch ALL Terminals (Full System)" - Everything at once!

### Option 2: Individual Terminal Watchers
Run any PowerShell watcher directly:
```powershell
pwsh data/terminal_watchers/watch_claude_terminal.ps1
pwsh data/terminal_watchers/watch_errors_terminal.ps1
# etc...
```

### Option 3: Master Python Launcher
```powershell
python scripts/launch_all_terminal_watchers.py
```
This opens all terminals in separate console windows!

### Option 4: Validate Setup
```powershell
python scripts/activate_live_terminal_routing.py --validate
```
Checks routing config, watcher scripts, task entries, and log files.

## Integration with Your Code

Use the terminal integration module in your scripts:

```python
from src.output.terminal_integration import (
    route_to_terminal,
    to_claude,
    to_errors,
    to_tasks,
    route_agent_output,
    setup_terminal_logging
)

# Direct routing
to_claude("Claude is analyzing the codebase...")
to_errors("ERROR: Configuration file not found")
to_tasks("Processing task #42...")

# Context manager for agent sessions
with route_agent_output("Claude"):
    print("This goes to Claude terminal!")
    print("All output is automatically routed")

# Automatic routing via logging
setup_terminal_logging()
logger = logging.getLogger(__name__)
logger.info("This will auto-route to appropriate terminal")
logger.error("Errors go to error terminal automatically")
```

## Terminal Mapping

Agent Terminals:
- 🧠 Claude: Claude Code agent output
- 🧩 Copilot: GitHub Copilot suggestions
- 🧠 Codex: OpenAI Codex transformations
- 🏗️ ChatDev: Multi-agent team coordination
- 🏛️ AI Council: Consensus and voting
- 🔗 Intermediary: Inter-agent communication

Operational Terminals:
- 🔥 Errors: All error output
- 💡 Suggestions: Recommendations and hints
- ✅ Tasks: Task execution and queues
- 🧪 Tests: Pytest output and coverage
- 🎯 Zeta: Autonomous cycles
- 🤖 Agents: General agent coordination
- 📊 Metrics: Health and performance
- ⚡ Anomalies: Unusual events
- 🔮 Future: Planning and roadmap
- 🏠 Main: General output

## Next Steps

1. Run demo: `python src/output/terminal_integration.py`
2. Start watchers: Use VSCode task or master launcher
3. Integrate into your scripts: Add terminal routing calls
4. Watch the magic: See output flowing to correct terminals!

## Log Files Location

All terminal output is logged to:
`{output_dir}/<terminal_name>.log`

## Troubleshooting

- If watchers don't start: Check PowerShell execution policy
- If logs are empty: Ensure scripts are using terminal integration module
- If output not routing: Check keyword matching in TERMINAL_ROUTES

## Architecture

```
Your Python Scripts
    ↓
Terminal Integration Module (terminal_integration.py)
    ↓
Route by keywords/context
    ↓
Write to terminal log files (data/terminal_logs/*.log)
    ↓
PowerShell watchers tail logs (data/terminal_watchers/*.ps1)
    ↓
VSCode terminal windows show live output
```

Now your terminals are ALIVE! 🎉
"""

    quick_ref_file = root / "docs" / "LIVE_TERMINAL_ROUTING_GUIDE.md"
    quick_ref_file.write_text(quick_ref, encoding="utf-8")
    print(f"   ✓ Quick reference: {quick_ref_file}")

    # Summary
    print("\n✨ Live Terminal Routing Activated!")
    print("=" * 70)
    print("\n📁 Generated Files:")
    print(f"   - {len(generated_watchers)} PowerShell watchers in {watcher_dir}")
    print(f"   - VSCode tasks in {tasks_file}")
    print(f"   - Master launcher: {launcher_file}")
    print(f"   - Quick guide: {quick_ref_file}")

    print("\n🚀 Next Steps:")
    print("   1. Run demo: python src/output/terminal_integration.py")
    print("   2. Start watchers: Ctrl+Shift+P → Tasks: Run Task → Watch All Agent Terminals")
    print("   3. See the magic: Your terminals now show LIVE output!")

    print(f"\n📖 Full guide: {quick_ref_file}")
    print("\n✅ Setup complete!")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Activate or validate live terminal routing.")
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate terminal routing artifacts without regenerating them.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    repo_root = Path(__file__).parent.parent
    if args.validate:
        raise SystemExit(validate_terminal_routing(repo_root))
    main()
