#!/usr/bin/env python3
"""Generate the next autonomous cultivation action from harvested signals."""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert signal report into action lists")
    parser.add_argument(
        "--signals",
        type=Path,
        default=Path("state/reports/multi_repo_signals.json"),
        help="Signal report generated by scripts/multi_repo_signal_harvester.py",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress the printed summary",
    )
    return parser.parse_args()


def load_signals(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Signal file missing: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def choose_action(signals: dict[str, Any]) -> dict[str, str]:
    repos = signals.get("repos", {})
    candidate = None
    max_errors = -1
    for label, payload in repos.items():
        errors = int(payload.get("lint_errors_count", 0))
        if errors > max_errors:
            max_errors = errors
            candidate = (label, payload)

    if candidate and max_errors > 0:
        label, payload = candidate
        return {
            "action": "run lint fix",
            "repo": label,
            "command": "python -m ruff check --select=F401,F821,E999 --fix",
        }

    return {
        "action": "review quest queue",
        "command": "python scripts/quest_processor.py --next-action",
        "note": "No lint errors detected, move to quest-aligned work",
    }


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    args = parse_args()

    try:
        signals = load_signals(args.signals)
    except Exception as exc:
        logger.error("Failed to load signals: %s", exc)
        return 1

    action = choose_action(signals)

    if not args.quiet:
        print("Autonomous action selected:")
        for key, value in action.items():
            print(f"  {key}: {value}")
    else:
        logger.info("Action: %s", action)

    Path("state/reports/last_autonomous_action.json").write_text(json.dumps(action, indent=2), encoding="utf-8")

    print(action.get("command"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
