#!/usr/bin/env python3
"""Cleanup Duplicate Placeholder Quests

Cancels duplicate 'Fix ValueError: Test error for workflow' placeholder quests
that were autogenerated but are not real bugs.

OmniTag: [cleanup, quests, maintenance]
"""

import json
from datetime import datetime
from pathlib import Path


def cleanup_duplicate_quests():
    """Cancel duplicate placeholder quests."""
    quest_file = Path("src/Rosetta_Quest_System/quests.json")
    quests = json.load(quest_file.open())

    # Find ValueError test error placeholders
    placeholder_title = "Fix ValueError: Test error for workflow..."
    placeholders = [
        q for q in quests if q.get("title") == placeholder_title and q.get("status") in ("active", "in_progress")
    ]

    print(f"Found {len(placeholders)} duplicate placeholder quests")

    # Cancel all but keep one for reference
    cancelled_count = 0
    for quest in placeholders:
        quest["status"] = "cancelled"
        quest["updated_at"] = datetime.now().isoformat()
        if "history" not in quest:
            quest["history"] = []
        quest["history"].append(
            {
                "status": "cancelled",
                "timestamp": datetime.now().isoformat(),
                "note": "Duplicate placeholder quest - autogenerated test error",
            }
        )
        cancelled_count += 1

    # Save updated quests
    with quest_file.open("w") as f:
        json.dump(quests, f, indent=2)

    print(f"✅ Cancelled {cancelled_count} duplicate placeholder quests")
    print(f"📊 Remaining active quests: {sum(1 for q in quests if q.get('status') in ('active', 'in_progress'))}")


if __name__ == "__main__":
    cleanup_duplicate_quests()
