#!/usr/bin/env python3
"""Generate missing __init__.py files with spine-aware templates.

This script creates __init__.py files for directories missing them,
using intelligent templates based on directory purpose.

Usage:
    python scripts/generate_missing_inits.py [--dry-run] [--template=basic|spine]
"""

import argparse
from pathlib import Path

# Deprecated typing aliases replaced with built-ins

# Directories to skip (not Python packages)
SKIP_DIRS = {
    "__pycache__",
    ".git",
    ".venv",
    "venv",
    "node_modules",
    ".pytest_cache",
    ".mypy_cache",
    "htmlcov",
    "build",
    "dist",
    "performance_data",  # Data directory, not a package
    "data",  # Data directory
    "RECEIPTS",  # Documentation receipts
}

# Directories that are legacy/archived (minimal init)
LEGACY_DIRS = {
    "legacy",
    "archived_20251225",
    "consolidation_20251211",
    "cleanup_backup",
    "20251009_124818",
}


def get_directory_category(path: Path) -> str:
    """Categorize directory by purpose."""
    name = path.name.lower()
    parts = path.parts

    # Legacy/archived
    if any(legacy in parts for legacy in LEGACY_DIRS):
        return "legacy"

    # Documentation
    if "docs" in parts or "documentation" in name:
        return "docs"

    # Tools and utilities
    if "tools" in parts or "utils" in parts:
        return "tools"

    # Missing/placeholder (needs attention)
    if "missing" in name or "placeholder" in name:
        return "placeholder"

    # Web/extension
    if "web" in name or "extension" in name or "vscode" in name:
        return "extension"

    # Output/reports
    if "output" in name or "reports" in name:
        return "output"

    # Evaluation/optimization
    if "evaluation" in name or "optimization" in name:
        return "analysis"

    # Core modules (orchestration, integration, etc.)
    return "core"


def generate_init_content(path: Path, category: str, template: str = "spine") -> str:
    """Generate __init__.py content based on category and template."""
    module_name = path.name
    relative_path = path.relative_to(Path("src"))

    # Get parent module for context (use forward slashes for cross-platform)
    parent_parts = relative_path.parts
    parent_context = " > ".join(parent_parts) if len(parent_parts) > 1 else "Root"
    # Use forward slashes in paths (cross-platform, no escape issues)
    path_str = str(relative_path).replace("\\", "/")

    if template == "basic":
        # Minimal template
        return f'"""{module_name.replace("_", " ").title()} module."""\n'

    # Spine-aware template
    templates = {
        "legacy": f'''"""Legacy/archived module: {module_name}

This module is archived and maintained for historical reference.
It may be outdated or deprecated.

Location: {path_str}
"""

# Legacy module - minimal exports
__all__ = []
''',
        "docs": f'''"""Documentation module: {module_name}

Contains documentation, receipts, or reference materials.

Location: {path_str}
"""

# Documentation package - not executable code
__all__ = []
''',
        "tools": f'''"""Tools and utilities: {module_name}

Helper tools and utility functions for the NuSyQ-Hub system.

Location: {path_str}
Parent: {parent_context}
"""

# Auto-generated by scripts/generate_missing_inits.py
# Public exports are promoted through src/spine/module_registry.json.

__all__ = []
''',
        "placeholder": f'''"""Placeholder module: {module_name}

⚠️  This module appears to be missing or incomplete.
It should be reviewed and either:
  1. Properly implemented with content
  2. Removed if obsolete
  3. Documented in src/spine/module_registry.json

Location: {path_str}
"""

# Placeholder - needs implementation or removal
__all__ = []
''',
        "extension": f'''"""Extension module: {module_name}

Integration or extension for external systems.

Location: {path_str}
"""

# Auto-generated by scripts/generate_missing_inits.py
# Public exports are promoted through src/spine/module_registry.json.

__all__ = []
''',
        "output": f'''"""Output and reports: {module_name}

Directory for generated output files, reports, and artifacts.

Location: {path_str}
"""

# Output directory - not a code package
__all__ = []
''',
        "analysis": f'''"""Analysis module: {module_name}

Code analysis, evaluation, or optimization tools.

Location: {path_str}
Parent: {parent_context}
"""

# Auto-generated by scripts/generate_missing_inits.py
# Public exports are promoted through src/spine/module_registry.json.

__all__ = []
''',
        "core": f'''"""NuSyQ-Hub module: {module_name}

Core system module for the NuSyQ-Hub ecosystem.

Location: {path_str}
Parent: {parent_context}

This module is spine-wired. See src/spine/module_registry.json
for centralized configuration and public API definition.
"""

# Auto-generated by scripts/generate_missing_inits.py
# To add public API, update src/spine/module_registry.json

__all__ = []
''',
    }

    return templates.get(category, templates["core"])


def find_missing_init_dirs(base_path: Path) -> list[Path]:
    """Find all directories missing __init__.py files."""
    missing = []

    for dirpath in base_path.rglob("*"):
        if not dirpath.is_dir():
            continue

        # Skip excluded directories
        if any(skip in dirpath.parts for skip in SKIP_DIRS):
            continue

        # Check if __init__.py exists
        init_file = dirpath / "__init__.py"
        if not init_file.exists():
            missing.append(dirpath)

    return sorted(missing)


def generate_init_files(
    dry_run: bool = False, template: str = "spine", base_path: Path | None = None
) -> dict[str, int]:
    """Generate missing __init__.py files.

    Returns:
        Statistics dictionary with counts
    """
    if base_path is None:
        base_path = Path("src")

    missing_dirs = find_missing_init_dirs(base_path)

    stats = {
        "total_dirs": len(list(base_path.rglob("*"))),
        "missing_init": len(missing_dirs),
        "generated": 0,
        "skipped": 0,
        "by_category": {},
    }

    print(f"🔍 Found {stats['missing_init']} directories without __init__.py")
    print(f"   Template: {template}")
    print(f"   Dry run: {dry_run}")
    print()

    for dirpath in missing_dirs:
        category = get_directory_category(dirpath)
        stats["by_category"][category] = stats["by_category"].get(category, 0) + 1

        init_file = dirpath / "__init__.py"
        content = generate_init_content(dirpath, category, template)

        if dry_run:
            print(f"[DRY RUN] Would create {init_file}")
            print(f"          Category: {category}")
            stats["skipped"] += 1
        else:
            init_file.write_text(content, encoding="utf-8")
            print(f"✅ Created {init_file}")
            print(f"   Category: {category}")
            stats["generated"] += 1

    return stats


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Generate missing __init__.py files with spine-aware templates")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be created without actually creating files",
    )
    parser.add_argument(
        "--template",
        choices=["basic", "spine"],
        default="spine",
        help="Template style to use (default: spine)",
    )
    parser.add_argument(
        "--base-path",
        type=Path,
        default=Path("src"),
        help="Base directory to scan (default: src)",
    )

    args = parser.parse_args()

    print("=" * 60)
    print("🧬 NuSyQ-Hub Spine Init Generator")
    print("=" * 60)
    print()

    stats = generate_init_files(dry_run=args.dry_run, template=args.template, base_path=args.base_path)

    print()
    print("=" * 60)
    print("📊 Generation Summary")
    print("=" * 60)
    print(f"Total directories scanned: {stats['total_dirs']}")
    print(f"Missing __init__.py files: {stats['missing_init']}")

    if args.dry_run:
        print(f"Would generate: {stats['skipped']}")
    else:
        print(f"Generated: {stats['generated']}")

    print("\nBy category:")
    for category, count in sorted(stats["by_category"].items()):
        print(f"  {category:15} {count:3} files")

    if not args.dry_run and stats["generated"] > 0:
        print()
        print("✅ All missing __init__.py files created!")
        print()
        print("Next steps:")
        print("  1. Review generated files")
        print("  2. Update src/spine/module_registry.json with public APIs")
        print("  3. Run: python scripts/start_nusyq.py hygiene --fast")
        print("  4. Commit changes")
    elif args.dry_run:
        print()
        print("💡 Run without --dry-run to actually create files")


if __name__ == "__main__":
    main()
