"""Generate per-directory commit batch scripts for large working trees.

This script inspects `git status --porcelain` and groups changed files by
top-level directory. For each group it emits a small Python runner script in
`scripts/batches/` that, when executed, will create a branch, add the files,
commit and push the branch. Files are chunked to `max_files_per_batch` to
avoid huge commits.

Usage:
  python scripts/generate_commit_batches.py

Outputs:
  - scripts/batches/commit_batch_<n>.py
  - scripts/batches/batches.json  (summary manifest)
  - README at scripts/batches/README.md with instructions
"""

import json
import os
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BATCH_DIR = REPO / "scripts" / "batches"
MAX_FILES_PER_BATCH = 60


def git_changed_files(repo: Path):
    res = subprocess.run(["git", "-C", str(repo), "status", "--porcelain"], capture_output=True, text=True)
    out = res.stdout.splitlines()
    files = []
    for line in out:
        line = line.strip()
        if not line:
            continue
        # status format: XY <file> or ?? <file>
        parts = line.split(None, 1)
        if len(parts) == 1:
            continue
        path = parts[1].strip()
        files.append(path)
    return files


def top_level(path: str):
    p = Path(path)
    parts = p.parts
    return parts[0] if len(parts) > 1 else "."


def chunk_list(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i : i + n]


def write_batch_script(batch_index: int, files: list[str], repo: Path, branch_prefix: str = "feature/batch") -> Path:
    BATCH_DIR.mkdir(parents=True, exist_ok=True)
    script_path = BATCH_DIR / f"commit_batch_{batch_index:03d}.py"
    branch = f"{branch_prefix}-{batch_index:03d}"
    content = f"""#!/usr/bin/env python3
import subprocess
from pathlib import Path
repo = Path(__file__).resolve().parents[2]
branch = '{branch}'
files = {json.dumps(files, indent=2)}

def run(cmd):
    print('RUN:', ' '.join(cmd))
    res = subprocess.run(cmd, cwd=str(repo))
    if res.returncode != 0:
        raise SystemExit(res.returncode)

run(['git', '-C', str(repo), 'checkout', '-b', branch])
for f in files:
    run(['git', '-C', str(repo), 'add', f])
run(['git', '-C', str(repo), 'commit', '-m', f'batched(commit): add {len(files)} files from batch {batch_index:03d}'])
run(['git', '-C', str(repo), 'push', '-u', 'origin', branch])
print('Batch', branch, 'pushed')
"""
    script_path.write_text(content, encoding="utf-8")
    if os.name != "nt":
        script_path.chmod(0o755)
    return script_path


def main():
    files = git_changed_files(REPO)
    if not files:
        print("No changed files found")
        return

    groups: dict[str, list[str]] = {}
    for f in files:
        key = top_level(f)
        groups.setdefault(key, []).append(f)

    batches = []
    idx = 1
    for key, flist in sorted(groups.items()):
        # chunk per-key if too large
        if len(flist) <= MAX_FILES_PER_BATCH:
            script = write_batch_script(idx, flist, REPO)
            batches.append(
                {
                    "index": idx,
                    "key": key,
                    "count": len(flist),
                    "script": str(script.relative_to(REPO)),
                }
            )
            idx += 1
        else:
            for chunk in chunk_list(flist, MAX_FILES_PER_BATCH):
                script = write_batch_script(idx, chunk, REPO)
                batches.append(
                    {
                        "index": idx,
                        "key": key,
                        "count": len(chunk),
                        "script": str(script.relative_to(REPO)),
                    }
                )
                idx += 1

    manifest = {"total_batches": len(batches), "batches": batches}
    (BATCH_DIR / "batches.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    readme = BATCH_DIR / "README.md"
    readme.write_text(
        """Batches generated by scripts/generate_commit_batches.py

To run a batch, execute (from repo root):

python scripts/batches/commit_batch_001.py

Review the generated scripts before running. Each script creates a branch, commits the listed files, and pushes the branch.
""",
        encoding="utf-8",
    )

    print(f"Generated {len(batches)} batches in {BATCH_DIR}")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
