"""test_audit_game — PyGame prototype generated by the game development pipeline.

A standalone PyGame game for testing and auditing game pipeline output.
Generated: 2026-02-25 via GameDevPipeline.

Run directly: python -m src.games.test_audit_game.main
"""

# Not intended for import as a library — standalone game only.
__all__: list[str] = []
