"""
app/game_engine/crafting_engine.py — R4 Crafting System
=========================================================
Combine raw components to create custom exploits, consumables, and tools.
Components are found by exploring nodes, dropped by dungeon enemies, or
purchased at the bank/market.

State is stored in gs.flags:
    "components"  : { component_id: quantity }
    "inventory"   : { item_id: quantity }      (crafted/consumable items)
    "active_buffs": [ { id, effect, remaining_commands } ]

Wire format compatible: all public methods return List[dict] with t/s keys.
"""
from __future__ import annotations

import random
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Wire helpers (module-local to avoid circular import)
# ---------------------------------------------------------------------------

def _sys(s: str) -> dict:   return {"t": "system",  "s": s}
def _dim(s: str) -> dict:   return {"t": "dim",     "s": s}
def _ok(s: str) -> dict:    return {"t": "success", "s": s}
def _err(s: str) -> dict:   return {"t": "error",   "s": s}
def _info(s: str) -> dict:  return {"t": "info",    "s": s}
def _lore(s: str) -> dict:  return {"t": "lore",    "s": s}
def _warn(s: str) -> dict:  return {"t": "warn",    "s": s}


# ---------------------------------------------------------------------------
# Component definitions (20 raw materials)
# ---------------------------------------------------------------------------

COMPONENTS: Dict[str, Dict] = {
    "memory_shard": {
        "name": "Memory Shard",
        "description": "Crystallised RAM fragments. Core crafting material.",
        "rarity": "common",
        "lore": "Broken off from a NexusCorp server rack during a forced shutdown.",
    },
    "trace_dust": {
        "name": "Trace Dust",
        "description": "Residue left by trace daemons. Useful for counter-surveillance.",
        "rarity": "common",
        "lore": "Collected by running silent commands while the trace is active.",
    },
    "nexus_fragment": {
        "name": "Nexus Fragment",
        "description": "Shards from NexusCorp infrastructure code.",
        "rarity": "uncommon",
        "lore": "Nexus Corp wrote three billion lines. You're recycling the useful ones.",
    },
    "void_crystal": {
        "name": "Void Crystal",
        "description": "Compressed null-space data. Dense information carrier.",
        "rarity": "uncommon",
        "lore": "Forms spontaneously in areas of high data entropy. Node-7 has some.",
    },
    "chimera_byte": {
        "name": "CHIMERA Byte",
        "description": "A fragment of CHIMERA's offensive payload. Handle with care.",
        "rarity": "rare",
        "lore": "Extracted during the chimera_exploited story beat. Still warm.",
    },
    "resistance_token": {
        "name": "Resistance Token",
        "description": "Proof of contribution to the underground. Symbolically potent.",
        "rarity": "uncommon",
        "lore": "ADA mints these for operatives who complete field missions.",
    },
    "entropy_seed": {
        "name": "Entropy Seed",
        "description": "Chaotic data kernel. Useful in stealth and disruption recipes.",
        "rarity": "common",
        "lore": "High-entropy data generated by running Monte Carlo simulations offline.",
    },
    "protocol_ghost": {
        "name": "Protocol Ghost",
        "description": "Dead network protocol instance. Can be reanimated for covert comms.",
        "rarity": "rare",
        "lore": "RAVEN describes them as 'packets that forgot to die'.",
    },
    "quantum_bit": {
        "name": "Quantum Bit",
        "description": "Single qubit: simultaneously zero and one. Powerful catalyst.",
        "rarity": "uncommon",
        "lore": "Borrowed from LM Studio's experimental model quantisation layer.",
    },
    "signal_noise": {
        "name": "Signal Noise",
        "description": "Raw electromagnetic interference. Surprisingly versatile.",
        "rarity": "common",
        "lore": "Scraped from unshielded cables in the NexusCorp server room.",
    },
    "darknet_token": {
        "name": "Darknet Token",
        "description": "Anonymous transaction certificate from the underground market.",
        "rarity": "uncommon",
        "lore": "Spendable once. Value: whatever the buyer and seller agree it is.",
    },
    "ghost_key": {
        "name": "Ghost Key",
        "description": "Asymmetric key pair with no registered origin. Untraceable.",
        "rarity": "rare",
        "lore": "ZERO handed you one. He said he had a thousand more.",
    },
    "neural_dust": {
        "name": "Neural Dust",
        "description": "Microscopic sensors — the physical layer of a social exploit.",
        "rarity": "uncommon",
        "lore": "Originally corporate wellness tech. Now: intelligence-gathering substrate.",
    },
    "data_shard": {
        "name": "Data Shard",
        "description": "Generic data fragment. Useful in many intermediate recipes.",
        "rarity": "common",
        "lore": "Exfiltrated from routine scan operations.",
    },
    "encrypted_cache": {
        "name": "Encrypted Cache",
        "description": "Pre-packaged encrypted payload blob.",
        "rarity": "uncommon",
        "lore": "Someone encrypted this. You don't know who. That's the point.",
    },
    "bio_circuit": {
        "name": "Bio-Circuit",
        "description": "Organic computing substrate. Strange resonance with neural nets.",
        "rarity": "rare",
        "lore": "NexusCorp's R&D division made these. They disappeared from the manifest.",
    },
    "lag_crystal": {
        "name": "Lag Crystal",
        "description": "Crystallised network latency. Useful for timing disruption.",
        "rarity": "common",
        "lore": "Found in every overloaded NexusCorp routing table.",
    },
    "shadow_byte": {
        "name": "Shadow Byte",
        "description": "Byte with no memory address. Exists outside normal memory maps.",
        "rarity": "rare",
        "lore": "SERENA indexed this. Then the index entry disappeared.",
    },
    "corp_token": {
        "name": "Corp Token",
        "description": "Stolen corporate authentication token. Short TTL.",
        "rarity": "uncommon",
        "lore": "Expires in 24 hours. Whatever you're going to do, do it now.",
    },
    "fractal_seed": {
        "name": "Fractal Seed",
        "description": "Self-replicating data pattern. Unpredictable but powerful.",
        "rarity": "rare",
        "lore": "CYPHER calls it 'compressed infinity'. He might not be wrong.",
    },
}


# ---------------------------------------------------------------------------
# Recipe definitions (12 recipes)
# ---------------------------------------------------------------------------

RECIPES: Dict[str, Dict] = {
    "phantom_exploit": {
        "name": "Phantom Exploit",
        "description": "Custom single-use exploit. +25 exploit success on next attempt.",
        "ingredients": {"chimera_byte": 2, "void_crystal": 1},
        "produces": "phantom_exploit",
        "quantity": 1,
        "effect": {"type": "buff", "stat": "exploit", "amount": 25, "duration": 1},
        "xp": 30,
        "skill": "security",
        "lore": "Built from CHIMERA's own offensive core. It doesn't know to block itself.",
        "icon": "💥",
    },
    "stealth_patch": {
        "name": "Stealth Patch",
        "description": "Instantly reduce trace level by 30. Single use.",
        "ingredients": {"trace_dust": 3, "entropy_seed": 1},
        "produces": "stealth_patch",
        "quantity": 1,
        "effect": {"type": "trace_reduction", "amount": 30},
        "xp": 20,
        "skill": "networking",
        "lore": "Overwrites your session fingerprint with pure noise.",
        "icon": "🌫",
    },
    "signal_booster": {
        "name": "Signal Booster",
        "description": "+50% XP from all commands for the next 5 commands.",
        "ingredients": {"signal_noise": 2, "quantum_bit": 1},
        "produces": "signal_booster",
        "quantity": 1,
        "effect": {"type": "xp_boost", "multiplier": 1.5, "duration": 5},
        "xp": 25,
        "skill": "hacking",
        "lore": "Tunes every operation to resonate with the network's own frequency.",
        "icon": "📶",
    },
    "neural_key": {
        "name": "Neural Key",
        "description": "Unlocks one hidden node access point (single use).",
        "ingredients": {"memory_shard": 3, "protocol_ghost": 1},
        "produces": "neural_key",
        "quantity": 1,
        "effect": {"type": "node_unlock", "target": "hidden"},
        "xp": 40,
        "skill": "hacking",
        "lore": "The key to a door that doesn't officially exist.",
        "icon": "🗝",
    },
    "chimera_disruptor": {
        "name": "CHIMERA Disruptor",
        "description": "Grants trace immunity from CHIMERA for 10 commands.",
        "ingredients": {"chimera_byte": 3, "resistance_token": 2, "void_crystal": 1},
        "produces": "chimera_disruptor",
        "quantity": 1,
        "effect": {"type": "immunity", "target": "chimera_trace", "duration": 10},
        "xp": 60,
        "skill": "security",
        "lore": "Makes you invisible to the thing that's been hunting you.",
        "icon": "🛡",
    },
    "ghost_payload": {
        "name": "Ghost Payload",
        "description": "Untraceable data packet — bypasses standard firewall rules.",
        "ingredients": {"ghost_key": 1, "shadow_byte": 1, "signal_noise": 1},
        "produces": "ghost_payload",
        "quantity": 1,
        "effect": {"type": "buff", "stat": "trace_reduction", "amount": 40, "duration": 3},
        "xp": 35,
        "skill": "networking",
        "lore": "ZERO's favourite. 'If they can't see the packet, they can't block it.'",
        "icon": "👁",
    },
    "trust_amplifier": {
        "name": "Trust Amplifier",
        "description": "+15 trust with the next agent you interact with.",
        "ingredients": {"neural_dust": 2, "corp_token": 1},
        "produces": "trust_amplifier",
        "quantity": 1,
        "effect": {"type": "buff", "stat": "trust_gain", "amount": 15, "duration": 1},
        "xp": 20,
        "skill": "social_engineering",
        "lore": "Manufactured credibility. The most dangerous kind.",
        "icon": "🤝",
    },
    "fractal_exploit": {
        "name": "Fractal Exploit",
        "description": "Self-replicating exploit — moderate boost over 5 commands.",
        "ingredients": {"fractal_seed": 1, "chimera_byte": 1, "data_shard": 2},
        "produces": "fractal_exploit",
        "quantity": 1,
        "effect": {"type": "buff", "stat": "exploit", "amount": 15, "duration": 5},
        "xp": 45,
        "skill": "security",
        "lore": "Rewrites itself each cycle. Unpredictable to defenders.",
        "icon": "🌀",
    },
    "lag_bomb": {
        "name": "Lag Bomb",
        "description": "Disrupts a target node's response for 3 commands — trace halted.",
        "ingredients": {"lag_crystal": 3, "entropy_seed": 2},
        "produces": "lag_bomb",
        "quantity": 1,
        "effect": {"type": "node_stun", "duration": 3},
        "xp": 30,
        "skill": "networking",
        "lore": "Weaponised latency. Inelegant but effective.",
        "icon": "💣",
    },
    "encrypted_key": {
        "name": "Encrypted Key",
        "description": "Decrypts one locked file or directory in the VFS.",
        "ingredients": {"encrypted_cache": 2, "ghost_key": 1},
        "produces": "encrypted_key",
        "quantity": 1,
        "effect": {"type": "vfs_unlock"},
        "xp": 35,
        "skill": "cryptography",
        "lore": "The question isn't what it unlocks. The question is who locked it.",
        "icon": "🔓",
    },
    "data_siphon": {
        "name": "Data Siphon",
        "description": "Passively collects 25 data units from the next node you visit.",
        "ingredients": {"data_shard": 3, "nexus_fragment": 2},
        "produces": "data_siphon",
        "quantity": 1,
        "effect": {"type": "data_harvest", "amount": 25},
        "xp": 25,
        "skill": "hacking",
        "lore": "Attaches to node traffic like a leech. Digital parasitism.",
        "icon": "📥",
    },
    "bio_exploit": {
        "name": "Bio-Exploit",
        "description": "Organic computing attack — +35 exploit, works on bio-mesh targets.",
        "ingredients": {"bio_circuit": 1, "chimera_byte": 2, "nexus_fragment": 1},
        "produces": "bio_exploit",
        "quantity": 1,
        "effect": {"type": "buff", "stat": "exploit", "amount": 35, "duration": 2},
        "xp": 55,
        "skill": "security",
        "lore": "NexusCorp's own R&D used against them. The loop is closed.",
        "icon": "🧬",
    },
}


# ---------------------------------------------------------------------------
# Drop table (for dungeon enemy loot)
# ---------------------------------------------------------------------------

_DROP_TABLE_BY_LEVEL = {
    # level_range: [( component_id, weight ), ...]
    (1, 5):   [
        ("memory_shard", 40), ("trace_dust", 35), ("signal_noise", 30),
        ("entropy_seed", 25), ("lag_crystal", 20), ("data_shard", 25),
    ],
    (6, 12):  [
        ("nexus_fragment", 30), ("void_crystal", 25), ("quantum_bit", 20),
        ("darknet_token", 20), ("neural_dust", 15), ("data_shard", 20),
        ("memory_shard", 20), ("resistance_token", 15),
    ],
    (13, 20): [
        ("chimera_byte", 25), ("ghost_key", 20), ("protocol_ghost", 20),
        ("shadow_byte", 15), ("bio_circuit", 12), ("corp_token", 18),
        ("encrypted_cache", 18), ("fractal_seed", 10),
    ],
}


def get_dungeon_drop(enemy_level: int) -> Optional[str]:
    """Return a random component id based on enemy level, or None for no drop."""
    if random.random() < 0.35:  # 35% drop chance
        return None
    for (lo, hi), table in _DROP_TABLE_BY_LEVEL.items():
        if lo <= enemy_level <= hi:
            components, weights = zip(*table)
            return random.choices(components, weights=list(weights), k=1)[0]
    # Fallback: high-level drops
    high = list(_DROP_TABLE_BY_LEVEL[(13, 20)])
    components, weights = zip(*high)
    return random.choices(components, weights=list(weights), k=1)[0]


# ---------------------------------------------------------------------------
# CraftingEngine
# ---------------------------------------------------------------------------

class CraftingEngine:
    """
    Manages component inventory, crafting recipes, and consumable item effects.

    State in gs.flags:
        "components"   : { component_id: int }
        "inventory"    : { item_id: int }
        "active_buffs" : [ { "id": str, "effect": dict, "remaining": int } ]
    """

    # ── State helpers ────────────────────────────────────────────────

    def _components(self, gs) -> dict:
        if "components" not in gs.flags:
            gs.flags["components"] = {}
        return gs.flags["components"]

    def _inventory(self, gs) -> dict:
        if "inventory" not in gs.flags:
            gs.flags["inventory"] = {}
        return gs.flags["inventory"]

    def _buffs(self, gs) -> list:
        if "active_buffs" not in gs.flags:
            gs.flags["active_buffs"] = []
        return gs.flags["active_buffs"]

    # ── Core operations ──────────────────────────────────────────────

    def add_component(self, component_id: str, qty: int, gs) -> List[dict]:
        """Add components to inventory (called by drops, missions, etc.)."""
        comp = COMPONENTS.get(component_id)
        if not comp:
            return [_err(f"  Unknown component: {component_id}")]
        comps = self._components(gs)
        comps[component_id] = comps.get(component_id, 0) + qty
        return [_ok(f"  +{qty}× {comp['name']} added to component inventory.")]

    def craft(self, recipe_id: str, gs) -> List[dict]:
        """Craft an item from a recipe. Deducts ingredients, adds to inventory."""
        recipe = RECIPES.get(recipe_id)
        if not recipe:
            close = [k for k in RECIPES if recipe_id in k or k.startswith(recipe_id[:4])]
            hint = f" Did you mean: {close[0]}?" if close else ""
            return [_err(f"  Unknown recipe: '{recipe_id}'.{hint}")]

        comps = self._components(gs)

        # Check ingredients
        missing = []
        for comp_id, needed in recipe["ingredients"].items():
            have = comps.get(comp_id, 0)
            if have < needed:
                comp_name = COMPONENTS.get(comp_id, {}).get("name", comp_id)
                missing.append(f"{comp_name}: need {needed}, have {have}")

        if missing:
            out = [_err(f"  Cannot craft {recipe['name']} — missing components:")]
            for m in missing:
                out.append(_dim(f"    - {m}"))
            out.append(_dim("  Use `craft components` to see what you have."))
            return out

        # Deduct ingredients
        for comp_id, needed in recipe["ingredients"].items():
            comps[comp_id] = comps.get(comp_id, 0) - needed

        # Add to inventory
        inv = self._inventory(gs)
        prod = recipe["produces"]
        inv[prod] = inv.get(prod, 0) + recipe["quantity"]

        # Award XP
        xp_gained = recipe.get("xp", 10)
        skill = recipe.get("skill", "hacking")
        if xp_gained > 0:
            try:
                gs.add_xp(xp_gained, skill)
            except Exception:
                pass

        out = [
            _sys(""),
            _ok(f"  ✓ CRAFTED: {recipe['icon']}  {recipe['name']}"),
            _dim(f"  {recipe['description']}"),
            _dim(""),
            _lore(f"  \"{recipe['lore']}\""),
            _dim(""),
            _info(f"  XP +{xp_gained} ({skill})"),
            _dim(f"  Use `craft use {prod}` to activate."),
            _dim(""),
        ]
        return out

    def use_item(self, item_id: str, gs) -> List[dict]:
        """Activate a consumable item from inventory."""
        inv = self._inventory(gs)
        if not inv.get(item_id, 0):
            return [_err(f"  You don't have any '{item_id}' in inventory.")]

        recipe = RECIPES.get(item_id)
        if not recipe:
            return [_err(f"  '{item_id}' has no use effect defined.")]

        inv[item_id] -= 1
        if inv[item_id] <= 0:
            del inv[item_id]

        effect = recipe.get("effect", {})
        etype = effect.get("type", "")
        out = [_ok(f"  ✓ USED: {recipe['icon']}  {recipe['name']}")]

        if etype == "buff":
            buffs = self._buffs(gs)
            buffs.append({
                "id": item_id,
                "effect": effect,
                "remaining": effect.get("duration", 1),
            })
            sign = "+" if effect.get("amount", 0) >= 0 else ""
            dur = effect.get("duration", 1)
            out.append(_info(f"  Buff active: {sign}{effect['amount']} {effect['stat']} for {dur} command(s)."))

        elif etype == "trace_reduction":
            current = gs.flags.get("trace_level", 0)
            reduction = effect.get("amount", 0)
            new_trace = max(0, current - reduction)
            gs.flags["trace_level"] = new_trace
            out.append(_info(f"  Trace level: {current} → {new_trace} (-{reduction})"))

        elif etype == "xp_boost":
            buffs = self._buffs(gs)
            buffs.append({
                "id": item_id,
                "effect": effect,
                "remaining": effect.get("duration", 5),
            })
            mult = effect.get("multiplier", 1.5)
            out.append(_info(f"  XP boost: ×{mult} for next {effect['duration']} commands."))

        elif etype == "node_unlock":
            gs.flags.setdefault("unlocked_nodes", []).append("hidden_annex")
            out.append(_info("  Hidden node access granted: hidden_annex unlocked."))

        elif etype == "immunity":
            buffs = self._buffs(gs)
            buffs.append({
                "id": item_id,
                "effect": effect,
                "remaining": effect.get("duration", 10),
            })
            out.append(_info(f"  Immunity: {effect.get('target', 'unknown')} for {effect['duration']} commands."))

        elif etype == "data_harvest":
            amount = effect.get("amount", 0)
            gs.flags["gear_data_pool"] = gs.flags.get("gear_data_pool", 0) + amount
            out.append(_info(f"  +{amount} data units harvested."))

        elif etype == "vfs_unlock":
            gs.flags.setdefault("unlocked_vfs_paths", []).append("locked")
            out.append(_info("  One locked VFS path unlocked."))

        elif etype == "node_stun":
            gs.flags["node_stunned_for"] = effect.get("duration", 3)
            out.append(_info(f"  Target node stunned for {effect['duration']} commands."))

        else:
            out.append(_dim(f"  Effect applied: {etype}"))

        out.append(_dim(""))
        return out

    def tick_buffs(self, gs) -> None:
        """
        Decrement buff counters by 1. Call once per executed command.
        Expired buffs are removed automatically.
        """
        buffs = self._buffs(gs)
        for b in buffs:
            b["remaining"] = max(0, b.get("remaining", 1) - 1)
        gs.flags["active_buffs"] = [b for b in buffs if b["remaining"] > 0]

    def get_active_buff_bonus(self, gs, stat: str) -> int:
        """Sum buff bonuses for a given stat from currently active buffs."""
        total = 0
        for b in self._buffs(gs):
            eff = b.get("effect", {})
            if eff.get("type") == "buff" and eff.get("stat") == stat:
                total += eff.get("amount", 0)
        return total

    def get_xp_multiplier(self, gs) -> float:
        """Return XP multiplier from active xp_boost buffs (stacks multiplicatively)."""
        mult = 1.0
        for b in self._buffs(gs):
            eff = b.get("effect", {})
            if eff.get("type") == "xp_boost":
                mult *= eff.get("multiplier", 1.0)
        return mult

    def has_immunity(self, gs, target: str) -> bool:
        """Check if an immunity buff is active for the given target."""
        for b in self._buffs(gs):
            eff = b.get("effect", {})
            if eff.get("type") == "immunity" and eff.get("target") == target:
                return True
        return False

    # ── Rendering ────────────────────────────────────────────────────

    def render_bench(self, gs) -> List[dict]:
        """Show all recipes with availability status."""
        comps = self._components(gs)
        inv = self._inventory(gs)

        out = [
            _sys(""),
            _sys("╔══════════════════════════════════════════════════════════╗"),
            _sys("║  CRAFTING BENCH — Combine Components, Build Weapons      ║"),
            _sys("╚══════════════════════════════════════════════════════════╝"),
            _dim(""),
            _info("  Usage: craft <recipe>  |  craft use <item>  |  craft components"),
            _dim(""),
        ]

        for recipe_id, recipe in RECIPES.items():
            # Check availability
            can_craft = all(
                comps.get(cid, 0) >= qty
                for cid, qty in recipe["ingredients"].items()
            )
            owned_qty = inv.get(recipe_id, 0)
            status = "[CRAFTABLE]" if can_craft else "[MISSING PARTS]"
            style = "success" if can_craft else "dim"

            out.append({"t": style, "s": f"  {recipe['icon']}  {recipe['name']}  {status}"})
            out.append(_dim(f"       {recipe['description'][:60]}"))

            ing_str = ", ".join(
                f"{qty}× {COMPONENTS.get(cid, {}).get('name', cid)}"
                for cid, qty in recipe["ingredients"].items()
            )
            out.append(_dim(f"       Ingredients: {ing_str}"))
            if owned_qty:
                out.append(_info(f"       In inventory: {owned_qty}"))
            out.append(_dim(f"       → craft {recipe_id}"))
            out.append(_dim(""))

        return out

    def render_components(self, gs) -> List[dict]:
        """Show all components the player has, grouped by rarity."""
        comps = self._components(gs)

        out = [
            _sys(""),
            _sys("  ── COMPONENT INVENTORY ─────────────────────────────────"),
            _dim(""),
        ]

        rarities = ["common", "uncommon", "rare"]
        found_any = False
        for rarity in rarities:
            items = [
                (cid, comp, comps.get(cid, 0))
                for cid, comp in COMPONENTS.items()
                if comp["rarity"] == rarity and comps.get(cid, 0) > 0
            ]
            if not items:
                continue
            found_any = True
            out.append(_sys(f"  [{rarity.upper()}]"))
            for cid, comp, qty in items:
                out.append(_info(f"    {qty:>3}×  {comp['name']:<22} — {comp['description'][:40]}"))
            out.append(_dim(""))

        if not found_any:
            out.append(_dim("  No components in inventory."))
            out.append(_dim("  Earn components: explore nodes, defeat dungeon enemies, complete missions."))
            out.append(_dim(""))

        # Show active buffs
        buffs = self._buffs(gs)
        if buffs:
            out.append(_sys("  ACTIVE BUFFS:"))
            for b in buffs:
                eff = b.get("effect", {})
                etype = eff.get("type", "unknown")
                recipe = RECIPES.get(b["id"], {})
                name = recipe.get("name", b["id"])
                rem = b.get("remaining", 0)
                out.append(_info(f"    {name} ({etype}) — {rem} command(s) remaining"))
            out.append(_dim(""))

        return out

    def render_inventory(self, gs) -> List[dict]:
        """Show crafted/consumable items in inventory."""
        inv = self._inventory(gs)
        out = [
            _sys(""),
            _sys("  ── CRAFTED ITEMS ─────────────────────────────────────────"),
            _dim(""),
        ]
        if not inv:
            out.append(_dim("  No crafted items. Use `craft bench` to see recipes."))
            out.append(_dim(""))
            return out
        for item_id, qty in inv.items():
            recipe = RECIPES.get(item_id, {})
            name = recipe.get("name", item_id)
            icon = recipe.get("icon", "•")
            desc = recipe.get("description", "")[:55]
            out.append(_info(f"  {icon}  {qty}×  {name}"))
            out.append(_dim(f"           {desc}"))
            out.append(_dim(f"           → craft use {item_id}"))
            out.append(_dim(""))
        return out


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

_engine: Optional[CraftingEngine] = None


def get_engine() -> CraftingEngine:
    global _engine
    if _engine is None:
        _engine = CraftingEngine()
    return _engine


if __name__ == "__main__":
    # Quick self-test
    class _FakeGS:
        level = 8
        skills = {"security": 30, "networking": 20}
        flags = {}

        def add_xp(self, amount, skill=None):
            print(f"  [XP] +{amount} {skill}")

    gs = _FakeGS()
    eng = CraftingEngine()

    # Add some components
    eng.add_component("chimera_byte", 3, gs)
    eng.add_component("void_crystal", 2, gs)
    eng.add_component("trace_dust", 4, gs)
    eng.add_component("entropy_seed", 1, gs)

    print("=== Components ===")
    for r in eng.render_components(gs):
        print(f"[{r['t']}] {r['s']}")

    print("\n=== Craft phantom_exploit ===")
    for r in eng.craft("phantom_exploit", gs):
        print(f"[{r['t']}] {r['s']}")

    print("\n=== Craft stealth_patch ===")
    for r in eng.craft("stealth_patch", gs):
        print(f"[{r['t']}] {r['s']}")

    print("\n=== Use phantom_exploit ===")
    for r in eng.use_item("phantom_exploit", gs):
        print(f"[{r['t']}] {r['s']}")

    print(f"\nXP multiplier: {eng.get_xp_multiplier(gs)}")
    print(f"Exploit buff bonus: {eng.get_active_buff_bonus(gs, 'exploit')}")

    # Test drop
    drops = [get_dungeon_drop(3) for _ in range(20)]
    print(f"\nDungeon drops (level 3): {[d for d in drops if d]}")
