#!/usr/bin/env python3
"""Module for JSON file persistence.
Generated by ChatDev + Ollama (qwen2.5-coder:7b)
"""
import json
from pathlib import Path

TASKS_FILE = Path(__file__).parent / "tasks.json"


def load_tasks():
    """Load tasks from JSON file."""
    try:
        with open(TASKS_FILE) as f:
            return json.load(f)
    except FileNotFoundError:
        return []


def save_tasks(tasks):
    """Save tasks to JSON file."""
    with open(TASKS_FILE, "w") as f:
        json.dump(tasks, f, indent=4)
