#!/usr/bin/env python3
"""AI Devlog Analyzer — Zero-token ops meets LLM intelligence.

Reads devlog.md and uses the LLM to produce:
  - Top 3 prioritized next actions
  - Implementation stubs for the top task
  - Updated todo.md entry

Usage:
    python scripts/ai_analyze.py              # full analysis
    python scripts/ai_analyze.py --quick      # just priorities
    python scripts/ai_analyze.py --generate   # generate implementation for top task
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from llm_client import LLMClient, Prompts

DEVLOG = Path("devlog.md")
TODO = Path("todo.md")
DEVLOG_ANALYSIS = Path("docs/AI_ANALYSIS.md")


def analyze(quick: bool = False, generate: bool = False):
    llm = LLMClient()
    print(f"[ai_analyze] Backend: {llm.backend_name}")

    if not DEVLOG.exists():
        print("[ai_analyze] devlog.md not found — nothing to analyze")
        return

    log_text = DEVLOG.read_text()
    print(f"[ai_analyze] Analyzing {len(log_text)} chars of devlog...")

    priorities = llm.generate(
        Prompts.devlog_priorities(log_text),
        system=(
            "You are a senior software architect reviewing a development log. "
            "Identify the 3 most impactful next tasks. "
            "Be specific: name files, functions, and exact changes. "
            "Format as numbered list."
        ),
        max_tokens=400,
    )

    print("\n" + "=" * 60)
    print("  AI DEVELOPMENT PRIORITIES")
    print("=" * 60)
    print(priorities)
    print("=" * 60 + "\n")

    if not quick:
        _save_analysis(priorities, log_text, llm)

    if generate:
        _generate_implementation(priorities, llm)


def _save_analysis(priorities: str, log_text: str, llm: LLMClient):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = f"""# AI Development Analysis — {ts}

## Priorities
{priorities}

## Devlog Summary
*Generated by AI from {len(log_text)} chars of devlog.md*

## How to act on these
1. Pick the top priority
2. Run: `python agents/llm_agent.py --demo` to test LLM generation
3. Create a task file in `tasks/` for the llm_agent to process
"""
    DEVLOG_ANALYSIS.parent.mkdir(exist_ok=True)
    DEVLOG_ANALYSIS.write_text(report)
    print(f"[ai_analyze] Saved analysis → {DEVLOG_ANALYSIS}")

    todo_entry = f"\n## AI Priorities — {ts}\n\n{priorities}\n"
    current = TODO.read_text() if TODO.exists() else "# TODO\n\n"
    TODO.write_text(current + todo_entry)
    print("[ai_analyze] Updated todo.md")


def _generate_implementation(priorities: str, llm: LLMClient):
    print("\n[ai_analyze] Generating implementation stub for top priority...")
    code = llm.generate(
        f"Based on this priority:\n{priorities.splitlines()[0] if priorities else 'implement next feature'}\n\n"
        f"Write a Python implementation stub (function or class) that starts to address this. "
        f"Include docstring and TODO comments for the key steps.",
        system=Prompts.SYSTEM_DEV,
        max_tokens=400,
    )
    stub_file = Path("agents/outputs/ai_generated_stub.py")
    stub_file.parent.mkdir(exist_ok=True)
    stub_file.write_text(
        f"# AI-generated stub — {datetime.now().isoformat()}\n# Top priority from devlog analysis\n\n{code}"
    )
    print(f"[ai_analyze] Saved implementation stub → {stub_file}")
    print("\n" + "-" * 50)
    print(code[:500])
    print("-" * 50)


def main():
    parser = argparse.ArgumentParser(description="AI Devlog Analyzer for DevMentor")
    parser.add_argument(
        "--quick", action="store_true", help="Print priorities only, no file saves"
    )
    parser.add_argument(
        "--generate", action="store_true", help="Generate implementation stub"
    )
    args = parser.parse_args()
    analyze(quick=args.quick, generate=args.generate)


if __name__ == "__main__":
    main()
