"""AI-generated menu helper functions for reducing cognitive complexity.

This module was autonomously generated by Ollama qwen2.5-coder:7b
as part of the automated code modernization initiative.
"""

from typing import Any


def extract_menu_options(menu_dict: object) -> list[str]:
    """Extracts menu options from a dictionary and returns them as a formatted list.

    Parameters
    ----------
        menu_dict (dict[str, str]): A dictionary where keys are option names and values are descriptions.

    Returns:
    -------
        list[str]: A list of formatted menu options.

    Raises:
    ------
        ValueError: If the input is not a dictionary or if it contains non-string values.

    """
    if not isinstance(menu_dict, dict):
        msg = "Input must be a dictionary."
        raise ValueError(msg)

    formatted_options: list[str] = []
    dictionary: dict[Any, Any] = menu_dict
    for option, description in dictionary.items():
        if not isinstance(option, str) or not isinstance(description, str):
            msg = "Dictionary keys and values must be strings."
            raise ValueError(msg)

        formatted_option = f"{option}: {description}"
        formatted_options.append(formatted_option)

    return formatted_options
