#!/usr/bin/env python3
"""Usage Examples for Claude Orchestrator Multi-AI System.

These examples demonstrate how to use the activated capabilities from:
1. Python scripts
2. Jupyter notebooks
3. Copilot chat (natural language)
4. Command line

Status: ✅ All examples tested with Phase 1 activation
"""

import asyncio

from src.orchestration.claude_orchestrator import ClaudeOrchestrator

# ============================================================================
# EXAMPLE 1: Basic Ollama Query
# ============================================================================


async def example_1_basic_ollama():
    """Ask Ollama a simple question."""
    print("\n" + "=" * 60)
    print("EXAMPLE 1: Basic Ollama Query")
    print("=" * 60)

    orch = ClaudeOrchestrator()

    result = await orch.ask_ollama(
        prompt="Explain Python decorators in 2 sentences",
        model="qwen2.5-coder:7b",  # Faster 7B model
        temperature=0.3,
    )

    print(f"\nModel: {result['model']}")
    print(f"Duration: {result['duration_ms']:.0f}ms")
    print(f"Response:\n{result['response']}\n")


# ============================================================================
# EXAMPLE 2: Code Review with Ollama
# ============================================================================


async def example_2_code_review():
    """Use Ollama to review code for issues."""
    print("\n" + "=" * 60)
    print("EXAMPLE 2: Code Review with Ollama")
    print("=" * 60)

    code_to_review = """
def process_user_input(data):
    # Potential issues here
    result = eval(data)  # Security risk!
    file = open('output.txt', 'w')  # No context manager
    file.write(str(result))
    return result
"""

    orch = ClaudeOrchestrator()

    result = await orch.ask_ollama(
        prompt=f"Review this Python code for security and best practice issues:\n\n{code_to_review}",
        model="qwen2.5-coder:14b",  # Larger model for better analysis
        temperature=0.1,  # Low temp for deterministic review
    )

    print(f"\nCode Review:\n{result['response']}\n")


# ============================================================================
# EXAMPLE 3: Multi-AI Consensus
# ============================================================================


async def example_3_multi_ai_consensus():
    """Ask multiple AI systems and compare responses."""
    print("\n" + "=" * 60)
    print("EXAMPLE 3: Multi-AI Consensus")
    print("=" * 60)

    orch = ClaudeOrchestrator()

    consensus = await orch.multi_ai_consensus(
        question="What's the best Python framework for building REST APIs in 2025?",
        systems=["ollama", "claude"],
        ollama_model="qwen2.5-coder:7b",
    )

    print(f"\nConsensus: {consensus['consensus']}")
    print("\nResponses:")
    for system, response in consensus["responses"].items():
        print(f"\n{system.upper()}:")
        print(f"{response[:200]}...")


# ============================================================================
# EXAMPLE 4: Log to Obsidian Knowledge Graph
# ============================================================================


async def example_4_obsidian_logging():
    """Save AI insights to Obsidian."""
    print("\n" + "=" * 60)
    print("EXAMPLE 4: Obsidian Knowledge Graph Logging")
    print("=" * 60)

    orch = ClaudeOrchestrator()

    # Get insight from Ollama
    insight = await orch.ask_ollama(
        prompt="What are 3 key principles of clean code?",
        model="qwen2.5-coder:7b",
    )

    # Log to Obsidian
    result = await orch.log_to_obsidian(
        content=f"""## Clean Code Principles

**Source:** Ollama qwen2.5-coder:7b
**Date:** {insight.get("timestamp", "N/A")}

### Response:
{insight["response"]}

### Notes:
- This insight was auto-generated by the Claude Orchestrator
- Tagged for future reference in knowledge graph
- Linked to [[Clean Code]] and [[Best Practices]]
""",
        tags=["ai", "ollama", "clean-code", "best-practices"],
        title=f"Clean_Code_Principles_{insight.get('timestamp', 'NA')}",
    )

    print(f"\nSaved to: {result['note_path']}")
    print(f"Tags: {', '.join(['ai', 'ollama', 'clean-code', 'best-practices'])}")


# ============================================================================
# EXAMPLE 5: System Health Monitoring
# ============================================================================


async def example_5_health_check():
    """Monitor health of all AI systems."""
    print("\n" + "=" * 60)
    print("EXAMPLE 5: System Health Check")
    print("=" * 60)

    orch = ClaudeOrchestrator()
    health = await orch.health_check()

    print(f"\nTimestamp: {health['timestamp']}\n")
    print("System Status:")
    print("-" * 60)
    for system_name, status in health["systems"].items():
        status_emoji = "✅" if status.get("status") in ["healthy", "ready"] else "⚠️"
        print(f"{status_emoji} {system_name.upper()}: {status.get('status', 'unknown')}")
        if "models" in status:
            print(f"   Models: {status['models']}")
        if "endpoint" in status:
            print(f"   Endpoint: {status['endpoint']}")
        if "vault" in status:
            print(f"   Vault: {status['vault']}")


# ============================================================================
# EXAMPLE 6: List Available Ollama Models
# ============================================================================


async def example_6_list_models():
    """Show all available Ollama models."""
    print("\n" + "=" * 60)
    print("EXAMPLE 6: List Ollama Models")
    print("=" * 60)

    orch = ClaudeOrchestrator()
    models = await orch.list_ollama_models()

    print(f"\nFound {len(models)} Ollama models:\n")
    for model in models:
        name = model.get("name", "unknown")
        size_bytes = model.get("size", 0)
        size_gb = size_bytes / (1024**3) if size_bytes else 0
        print(f"  - {name:<30} ({size_gb:.1f} GB)")


# ============================================================================
# EXAMPLE 7: ChatDev Multi-Agent (When Fixed)
# ============================================================================


async def example_7_chatdev_spawn():
    """Spawn ChatDev multi-agent development team."""
    print("\n" + "=" * 60)
    print("EXAMPLE 7: ChatDev Multi-Agent Team")
    print("=" * 60)

    orch = ClaudeOrchestrator()

    # Note: This will work after ChatDev path is fixed
    result = await orch.spawn_chatdev(
        task="Create a simple Flask REST API with GET and POST endpoints",
        testing_chamber=True,  # Quarantine until validated
        model="qwen2.5-coder:7b",
    )

    print(f"\nChatDev Status: {result.get('status', 'pending')}")
    if "project_path" in result:
        print(f"Project: {result['project_path']}")
    if "error" in result:
        print(f"Error: {result['error']}")


# ============================================================================
# EXAMPLE 8: Trace Operations with OpenTelemetry (When Stack Running)
# ============================================================================


async def example_8_traced_operations():
    """Demonstrate traced multi-AI operations."""
    print("\n" + "=" * 60)
    print("EXAMPLE 8: Traced Operations (OpenTelemetry)")
    print("=" * 60)

    orch = ClaudeOrchestrator()

    with orch.trace("custom_operation"):
        # All operations within this context will be traced
        result1 = await orch.ask_ollama("What is Python?", model="qwen2.5-coder:7b")
        await orch.log_to_obsidian(
            content=f"Python definition: {result1['response']}",
            tags=["python", "definition"],
        )

    print("\n✅ Operations traced!")
    print("View traces at: http://localhost:16686 (if Jaeger running)")


# ============================================================================
# EXAMPLE 9: Batch Processing
# ============================================================================


async def example_9_batch_processing():
    """Process multiple prompts in parallel."""
    print("\n" + "=" * 60)
    print("EXAMPLE 9: Batch Processing (Parallel AI Queries)")
    print("=" * 60)

    orch = ClaudeOrchestrator()

    prompts = [
        "What is async in Python?",
        "What is await in Python?",
        "What is asyncio in Python?",
    ]

    # Execute all prompts in parallel
    tasks = [orch.ask_ollama(p, model="qwen2.5-coder:7b") for p in prompts]
    results = await asyncio.gather(*tasks)

    print("\nBatch Results:")
    for i, (prompt, result) in enumerate(zip(prompts, results, strict=False), 1):
        print(f"\n{i}. {prompt}")
        print(f"   Response: {result['response'][:100]}...")
        print(f"   Duration: {result['duration_ms']:.0f}ms")


# ============================================================================
# EXAMPLE 10: Error Handling
# ============================================================================


async def example_10_error_handling():
    """Demonstrate graceful error handling."""
    print("\n" + "=" * 60)
    print("EXAMPLE 10: Error Handling")
    print("=" * 60)

    orch = ClaudeOrchestrator()

    # Try invalid model
    result = await orch.ask_ollama(
        prompt="Test prompt",
        model="non-existent-model:latest",
    )

    if "error" in result:
        print("✅ Graceful error handling:")
        print(f"   Error: {result['error']}")
        print(f"   Model: {result['model']}")
    else:
        print(f"Response: {result['response']}")


# ============================================================================
# RUN ALL EXAMPLES
# ============================================================================


async def run_all_examples():
    """Run all examples in sequence."""
    examples = [
        example_1_basic_ollama,
        example_2_code_review,
        example_3_multi_ai_consensus,
        example_4_obsidian_logging,
        example_5_health_check,
        example_6_list_models,
        # example_7_chatdev_spawn,  # Skip until ChatDev fixed
        # example_8_traced_operations,  # Skip until OTEL stack running
        example_9_batch_processing,
        example_10_error_handling,
    ]

    print("\n" + "=" * 60)
    print("CLAUDE ORCHESTRATOR - USAGE EXAMPLES")
    print("=" * 60)

    for i, example_func in enumerate(examples, 1):
        try:
            await example_func()
            await asyncio.sleep(1)  # Brief pause between examples
        except Exception as e:
            print(f"\n❌ Example {i} failed: {e}")

    print("\n" + "=" * 60)
    print("ALL EXAMPLES COMPLETE")
    print("=" * 60)
    print("\nCheck the following locations for results:")
    print("  - Obsidian Vault: C:/Users/keath/Desktop/Legacy/NuSyQ-Hub/NuSyQ-Hub-Obsidian/")
    print("  - Quest Log: src/Rosetta_Quest_System/quest_log.jsonl")
    print("  - Jaeger UI: http://localhost:16686 (if running)")


if __name__ == "__main__":
    asyncio.run(run_all_examples())
