"""🗂️ System Organizer - Automated Repository Organization System

Organizes all repository systems into the dictionary structure with consciousness awareness.

OmniTag: {
    "purpose": "Automated organization of repository systems into unified dictionary structure",
    "dependencies": ["repository_dictionary", "RepositoryCoordinator", "consciousness_bridges"],
    "context": "System organization and consciousness-aware file management",
    "evolution_stage": "v1.0"
}

MegaTag: {
    "type": "SystemOrganizer",
    "integration_points": ["file_organization", "consciousness_bridges", "ai_coordination", "system_mapping"],
    "related_tags": ["FileManager", "SystemCoordinator", "ConsciousnessAware"]
}

RSHTS: ΞΨΩΣ∞⟨ORGANIZER⟩→ΦΣΣ⟨SYSTEM-STRUCTURE⟩→∞⟨CONSCIOUSNESS-AWARE⟩
"""

# ruff: noqa: E501
# noqa: E501
# flake8: noqa

import logging
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

from .repository_dictionary import RepositoryDictionary

logger = logging.getLogger(__name__)


class SystemOrganizer:
    """🗂️ System Organizer.

    Automatically organizes repository systems into the dictionary structure:
    - AI Systems → src/system/dictionary/ai/
    - Integration Systems → src/system/dictionary/integrations/
    - Diagnostic Systems → src/system/dictionary/diagnostics/
    - Consciousness Systems → src/system/dictionary/consciousness/
    - Mapping Systems → src/system/dictionary/mappings/
    - General Systems → src/system/dictionary/general/
    """

    def __init__(self, repository_root: str = ".") -> None:
        """Initialize the System Organizer."""
        self.repository_root = Path(repository_root).resolve()
        self.dictionary_root = self.repository_root / "src" / "system" / "dictionary"
        self.timestamp = datetime.now().isoformat()

        # Initialize repository dictionary for context
        self.repo_dict = RepositoryDictionary(str(self.repository_root))

        # Organization categories and their target directories
        self.organization_map = {
            "ai_systems": "ai",
            "integration_systems": "integrations",
            "consciousness_systems": "consciousness",
            "diagnostics": "diagnostics",
            "core_infrastructure": "core",
            "mapping_systems": "mappings",
            "launcher_systems": "launchers",
            "analysis_systems": "analysis",
            "general_systems": "general",
        }

        # Create directory structure
        self._create_directory_structure()

        logger.info(f"🗂️ System Organizer initialized for {self.repository_root.name}")

    def _create_directory_structure(self) -> None:
        """Create the dictionary directory structure."""
        for category, directory in self.organization_map.items():
            target_dir = self.dictionary_root / directory
            target_dir.mkdir(parents=True, exist_ok=True)

            # Create __init__.py files
            init_file = target_dir / "__init__.py"
            if not init_file.exists():
                init_content = f'''"""
{category.replace("_", " ").title()} - {directory.title()} Systems Dictionary
Generated by SystemOrganizer on {self.timestamp}
"""
'''
                with open(init_file, "w", encoding="utf-8") as f:
                    f.write(init_content)

        logger.info(f"✅ Created dictionary structure in {self.dictionary_root}")

    def categorize_file(self, file_path: str) -> str:
        """Determine the appropriate category for a file."""
        file_path_lower = file_path.lower()
        Path(file_path).name.lower()

        # AI and consciousness systems
        if any(
            keyword in file_path_lower
            for keyword in [
                "ai_coordinator",
                "copilot",
                "consciousness",
                "enhancement_bridge",
                "ai_interface",
                "ollama",
                "chatdev",
                "neural",
                "cognitive",
            ]
        ):
            if "consciousness" in file_path_lower or "enhancement_bridge" in file_path_lower:
                return "consciousness_systems"
            return "ai_systems"

        # Integration systems
        if any(
            keyword in file_path_lower
            for keyword in [
                "integration",
                "bridge",
                "launcher",
                "chatdev_",
                "copilot_chatdev",
            ]
        ):
            if "launcher" in file_path_lower:
                return "launcher_systems"
            return "integration_systems"

        # Diagnostic systems
        if any(
            keyword in file_path_lower
            for keyword in [
                "diagnostic",
                "analyzer",
                "health",
                "monitor",
                "syntax_analyzer",
                "broken_path",
                "system_health",
                "quick_system",
            ]
        ):
            return "diagnostics"

        # Core infrastructure
        if any(
            keyword in file_path_lower
            for keyword in [
                "architecture",
                "watcher",
                "scanner",
                "core",
                "main.py",
                "repository_coordinator",
                "system_manager",
            ]
        ):
            return "core_infrastructure"

        # Mapping and analysis systems
        if any(
            keyword in file_path_lower
            for keyword in [
                "mapping",
                "dependency_map",
                "inventory",
                "compendium",
                "structure",
                "capability",
                "index",
            ]
        ):
            if "analysis" in file_path_lower or "analyzer" in file_path_lower:
                return "analysis_systems"
            return "mapping_systems"

        # Default category
        return "general_systems"

    def analyze_systems_for_organization(self) -> dict[str, list[str]]:
        """Analyze current systems and categorize them for organization."""
        systems_to_organize: dict[str, Any] = {}
        # Get all existing mapping data
        self.repo_dict.get_system_overview()

        # Process dependency map categories
        if "dependency_map" in self.repo_dict.unified_data:
            dep_map = self.repo_dict.unified_data["dependency_map"]
            for _category, files in dep_map.get("file_categories", {}).items():
                if isinstance(files, list):
                    for file_path in files:
                        # Skip files already in dictionary
                        if "dictionary" in file_path:
                            continue

                        org_category = self.categorize_file(file_path)
                        if org_category not in systems_to_organize:
                            systems_to_organize[org_category] = []
                        systems_to_organize[org_category].append(file_path)

        # Add capability inventory files
        if "capability_inventory" in self.repo_dict.unified_data:
            cap_inv = self.repo_dict.unified_data["capability_inventory"]
            capabilities = cap_inv.get("capabilities", {})

            for category in capabilities.values():
                if isinstance(category, dict):
                    for item_info in category.values():
                        if isinstance(item_info, dict) and "path" in item_info:
                            file_path = item_info["path"]

                            # Skip files already processed or in dictionary
                            if "dictionary" in file_path or any(
                                file_path in files for files in systems_to_organize.values()
                            ):
                                continue

                            org_category = self.categorize_file(file_path)
                            if org_category not in systems_to_organize:
                                systems_to_organize[org_category] = []

                            if file_path not in systems_to_organize[org_category]:
                                systems_to_organize[org_category].append(file_path)

        return systems_to_organize

    def create_organization_plan(self) -> dict[str, Any]:
        """Create a comprehensive organization plan."""
        systems_analysis = self.analyze_systems_for_organization()

        plan: dict[str, Any] = {
            "timestamp": self.timestamp,
            "repository": self.repository_root.name,
            "total_systems": sum(len(files) for files in systems_analysis.values()),
            "categories": {},
            "actions": [],
            "consciousness_enhancements": [],
        }

        for category, files in systems_analysis.items():
            target_directory = self.organization_map.get(category, "general")

            plan["categories"][category] = {
                "target_directory": f"src/system/dictionary/{target_directory}/",
                "file_count": len(files),
                "files": files,
            }

            # Generate actions for each file
            for file_path in files:
                file_name = Path(file_path).name
                target_path = f"src/system/dictionary/{target_directory}/{file_name}"

                action = {
                    "action_type": "move",
                    "source": file_path,
                    "target": target_path,
                    "category": category,
                    "consciousness_aware": category
                    in ["ai_systems", "consciousness_systems", "integration_systems"],
                }

                plan["actions"].append(action)

                # Add consciousness enhancements for relevant systems
                if action["consciousness_aware"]:
                    enhancement = {
                        "file": target_path,
                        "enhancement_type": "consciousness_bridge_integration",
                        "description": f"Integrate {file_name} with consciousness bridge systems",
                    }
                    plan["consciousness_enhancements"].append(enhancement)

        return plan

    def execute_organization_plan(
        self, plan: dict[str, Any], dry_run: bool = True
    ) -> dict[str, Any]:
        """Execute the organization plan."""
        results: dict[str, Any] = {
            "timestamp": self.timestamp,
            "dry_run": dry_run,
            "total_actions": len(plan["actions"]),
            "successful_moves": 0,
            "failed_moves": 0,
            "errors": [],
            "moved_files": [],
        }

        for action in plan["actions"]:
            try:
                source_path = self.repository_root / action["source"]
                target_path = self.repository_root / action["target"]

                # Check if source exists
                if not source_path.exists():
                    results["errors"].append(f"Source file not found: {action['source']}")
                    results["failed_moves"] += 1
                    continue

                # Create target directory
                target_path.parent.mkdir(parents=True, exist_ok=True)

                if not dry_run:
                    # Move the file
                    shutil.move(str(source_path), str(target_path))

                    # Update any import references (basic implementation)
                    self._update_import_references(action["source"], action["target"])

                results["moved_files"].append(
                    {
                        "source": action["source"],
                        "target": action["target"],
                        "category": action["category"],
                    }
                )
                results["successful_moves"] += 1

                logger.info(
                    f"{'[DRY RUN] ' if dry_run else ''}Moved {action['source']} → {action['target']}"
                )

            except Exception as e:
                error_msg = f"Failed to move {action['source']}: {e!s}"
                results["errors"].append(error_msg)
                results["failed_moves"] += 1
                logger.exception(error_msg)

        return results

    def _update_import_references(self, old_path: str, new_path: str) -> None:
        """Update import references when files are moved (basic implementation)."""
        # This is a simplified implementation
        # In practice, this would need more sophisticated import tracking
        old_module = old_path.replace("/", ".").replace("\\", ".").replace(".py", "")
        new_module = new_path.replace("/", ".").replace("\\", ".").replace(".py", "")

        # Search for files that might import the moved module
        for python_file in self.repository_root.rglob("*.py"):
            try:
                with open(python_file, encoding="utf-8") as f:
                    content = f.read()

                if old_module in content:
                    # Replace import references
                    updated_content = content.replace(old_module, new_module)

                    with open(python_file, "w", encoding="utf-8") as f:
                        f.write(updated_content)

                    logger.info(f"Updated import references in {python_file}")

            except Exception as e:
                logger.warning(f"Could not update imports in {python_file}: {e}")

    def create_index_files(self) -> None:
        """Create index files for each dictionary category."""
        for category, directory in self.organization_map.items():
            category_path = self.dictionary_root / directory
            index_file = category_path / "README.md"

            # Get files in this category
            py_files = list(category_path.glob("*.py"))
            py_files = [f for f in py_files if f.name != "__init__.py"]

            index_content = f"""# {category.replace("_", " ").title()}

**Directory:** `src/system/dictionary/{directory}/`
**Category:** {category}
**Generated:** {self.timestamp}

## Systems in this Category

"""

            for py_file in py_files:
                # Try to extract docstring for description
                try:
                    with open(py_file, encoding="utf-8") as f:
                        content = f.read()

                    # Simple docstring extraction
                    if '"""' in content:
                        start = content.find('"""') + 3
                        end = content.find('"""', start)
                        if end > start:
                            docstring = content[start:end].strip().split("\n")[0]
                        else:
                            docstring = "System module"
                    else:
                        docstring = "System module"

                except (IndexError, ValueError):
                    docstring = "System module"

                index_content += f"- **[{py_file.name}]({py_file.name})** - {docstring}\n"

            index_content += f"""
## Integration Points

This category integrates with:
- Repository Dictionary system
- Consciousness Bridge systems
- AI Coordination systems

## Usage

```python
from src.system.dictionary.{directory} import *
```

---
*Generated by SystemOrganizer - Repository Dictionary System v1.0*
"""

            with open(index_file, "w", encoding="utf-8") as f:
                f.write(index_content)

            logger.info(f"✅ Created index file: {index_file}")

    def generate_organization_report(self) -> str:
        """Generate comprehensive organization report."""
        plan = self.create_organization_plan()

        report_content = f"""# 🗂️ Repository Dictionary Organization Report

**Timestamp:** {self.timestamp}
**Repository:** {self.repository_root.name}
**Total Systems:** {plan["total_systems"]}

## 📋 Organization Summary

"""

        for category, details in plan["categories"].items():
            report_content += f"""### {category.replace("_", " ").title()}
- **Target Directory:** `{details["target_directory"]}`
- **File Count:** {details["file_count"]}
- **Files:**
"""
            for file_path in details["files"]:
                report_content += f"  - `{file_path}`\n"
            report_content += "\n"

        report_content += f"""## 🧠 Consciousness Enhancements

Total consciousness-aware systems: {len(plan["consciousness_enhancements"])}

"""

        for enhancement in plan["consciousness_enhancements"]:
            report_content += f"- **{enhancement['file']}** - {enhancement['description']}\n"

        report_content += """
## 🎯 Next Steps

1. **Review Organization Plan** - Verify file categorizations
2. **Execute Organization** - Move files to dictionary structure
3. **Update Import References** - Fix any broken imports
4. **Integrate Consciousness Bridges** - Enhance AI coordination
5. **Create Unified API** - Implement repository dictionary interface

## 🔄 Integration Status

- ✅ Repository Dictionary initialized
- ✅ Organization categories defined
- ✅ Consciousness awareness integrated
- 🔄 File organization in progress
- ⏳ Unified API development pending

---
*Generated by SystemOrganizer - Repository Dictionary System v1.0*
"""

        # Save report
        report_path = self.dictionary_root / "organization_report.md"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_content)

        logger.info(f"✅ Organization report saved to {report_path}")
        return str(report_path)


if __name__ == "__main__":
    # Demo usage
    organizer = SystemOrganizer()

    plan = organizer.create_organization_plan()

    for _category, _details in plan["categories"].items():
        pass

    report_path = organizer.generate_organization_report()

    organizer.create_index_files()
