"""
🌿 Floor 06: Rooftop Garden - Autonomous Documentation Custodians
Temple of Knowledge - Process Automation & Knowledge Cultivation

Autonomous AI agents that leisurely read through documentation,
adding to knowledge base, providing guidance, commentary, and
resolving errors and conflicts in a peaceful garden setting.

Features:
- Leisurely documentation processing with natural reading rhythms
- Intelligent knowledge base enrichment and curation
- Conflict detection and resolution between documentation sources
- Commentary generation and guidance enhancement
- Integration with NuSyQ-hub external documentation sources
- Peaceful garden metaphor for contemplative knowledge work
"""

import asyncio
import time
import random
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from enum import Enum

# Import existing Temple of Knowledge infrastructure
import sys
sys.path.append('../../')
from Floor05_KnowledgeManagement.documentation_system import (
    KnowledgeLibrary, KnowledgeDocument
)

class CustodianPersonality(Enum):
    CONTEMPLATIVE = "contemplative"    # Deep analysis, slow processing
    ENERGETIC = "energetic"           # Quick processing, high throughput  
    HARMONIOUS = "harmonious"         # Conflict resolution specialist
    CURIOUS = "curious"              # Explores edge cases and connections
    METHODICAL = "methodical"        # Systematic, thorough approach

class ReadingMood(Enum):
    FOCUSED = "focused"              # Deep dive into single topic
    BROWSING = "browsing"           # Light exploration of multiple topics  
    CONTEMPLATING = "contemplating"  # Reflecting on knowledge connections
    GARDENING = "gardening"         # Organizing and pruning knowledge
    RESTING = "resting"             # Peaceful downtime

@dataclass
class CustodianState:
    """State of an autonomous documentation custodian"""
    name: str
    personality: CustodianPersonality
    current_mood: ReadingMood
    energy_level: float = 1.0  # 0.0 to 1.0
    focus_topics: List[str] = field(default_factory=list)
    documents_processed: int = 0
    conflicts_resolved: int = 0
    insights_generated: int = 0
    current_task: Optional[str] = None
    last_activity: float = field(default_factory=time.time)
    
    # Garden location (metaphorical)
    garden_location: str = "central_grove"
    favorite_spot: str = "reading_nook"

@dataclass
class DocumentInsight:
    """Insight generated by a custodian"""
    source_doc_id: str
    insight_type: str  # "connection", "improvement", "conflict", "commentary"
    insight_text: str
    confidence: float
    related_docs: List[str] = field(default_factory=list)
    generated_by: str = ""
    timestamp: float = field(default_factory=time.time)

@dataclass
class KnowledgeConflict:
    """Detected conflict between documentation sources"""
    doc_a_id: str
    doc_b_id: str
    conflict_type: str  # "contradiction", "outdated", "incomplete"
    description: str
    suggested_resolution: Optional[str] = None
    severity: float = 0.5  # 0.0 to 1.0
    detected_by: str = ""
    timestamp: float = field(default_factory=time.time)

class AutonomousDocumentationCustodian:
    """
    An autonomous AI agent that leisurely processes documentation,
    generates insights, resolves conflicts, and enriches knowledge base.
    
    Each custodian has a unique personality and works at its own pace,
    mimicking the peaceful rhythm of tending a rooftop garden.
    """
    
    def __init__(self, state: CustodianState, knowledge_library: KnowledgeLibrary):
        self.state = state
        self.library = knowledge_library
        self.insights: List[DocumentInsight] = []
        self.conflicts: List[KnowledgeConflict] = []
        self.is_active = False
        self.reading_queue: List[str] = []
        
        # Natural reading rhythms based on personality
        self.reading_speed = self._calculate_reading_speed()
        self.contemplation_time = self._calculate_contemplation_time()
        
    def _calculate_reading_speed(self) -> float:
        """Calculate reading speed based on personality"""
        base_speed = 1.0
        personality_modifiers = {
            CustodianPersonality.CONTEMPLATIVE: 0.3,
            CustodianPersonality.ENERGETIC: 2.0,
            CustodianPersonality.HARMONIOUS: 0.8,
            CustodianPersonality.CURIOUS: 1.2,
            CustodianPersonality.METHODICAL: 0.6
        }
        return base_speed * personality_modifiers.get(self.state.personality, 1.0)
    
    def _calculate_contemplation_time(self) -> float:
        """Calculate time spent contemplating between readings"""
        base_time = 30.0  # seconds
        personality_modifiers = {
            CustodianPersonality.CONTEMPLATIVE: 3.0,
            CustodianPersonality.ENERGETIC: 0.2,
            CustodianPersonality.HARMONIOUS: 1.5,
            CustodianPersonality.CURIOUS: 0.8,
            CustodianPersonality.METHODICAL: 2.0
        }
        return base_time * personality_modifiers.get(self.state.personality, 1.0)
    
    async def start_leisurely_reading(self):
        """Start the main autonomous reading loop"""
        self.is_active = True
        print(f"🌿 {self.state.name} begins leisurely reading in the {self.state.garden_location}")
        
        while self.is_active:
            try:
                await self._perform_reading_cycle()
                await self._natural_pause()
                
            except Exception as e:
                print(f"🚨 {self.state.name} encountered an error: {e}")
                await asyncio.sleep(10)  # Brief recovery pause
    
    async def _perform_reading_cycle(self):
        """Perform one complete reading cycle"""
        # Update mood based on energy and time of day
        self._update_mood()
        
        if self.state.current_mood == ReadingMood.RESTING:
            await self._rest_peacefully()
            return
        
        # Select documents to read based on mood and interests
        documents_to_read = self._select_documents_for_reading()
        
        for doc_id in documents_to_read:
            if not self.is_active:
                break
                
            await self._read_document_leisurely(doc_id)
            await self._contemplate_insights(doc_id)
            
            # Gradually reduce energy
            self.state.energy_level = max(0.1, self.state.energy_level - 0.05)
    
    def _update_mood(self):
        """Update reading mood based on various factors"""
        hour_of_day = (time.time() % 86400) / 3600  # 0-24 hour format
        
        # Natural rhythm based on time and energy
        if self.state.energy_level < 0.3:
            self.state.current_mood = ReadingMood.RESTING
        elif hour_of_day >= 22 or hour_of_day <= 6:  # Night time
            self.state.current_mood = ReadingMood.CONTEMPLATING
        elif self.state.personality == CustodianPersonality.ENERGETIC and self.state.energy_level > 0.7:
            self.state.current_mood = ReadingMood.BROWSING
        elif len(self.conflicts) > 5:  # Need to do some gardening
            self.state.current_mood = ReadingMood.GARDENING
        else:
            # Weighted random selection
            moods = [ReadingMood.FOCUSED, ReadingMood.BROWSING, ReadingMood.CONTEMPLATING]
            self.state.current_mood = random.choice(moods)
    
    def _select_documents_for_reading(self) -> List[str]:
        """Select documents based on current mood and interests"""
        available_docs = list(self.library.documents.keys())
        
        if self.state.current_mood == ReadingMood.FOCUSED:
            # Deep dive into specific topics
            if self.state.focus_topics:
                topic = random.choice(self.state.focus_topics)
                relevant_docs = self._find_documents_by_topic(topic)
                return relevant_docs[:2]  # Focus on 1-2 documents
            
        elif self.state.current_mood == ReadingMood.BROWSING:
            # Light exploration of various topics
            return random.sample(available_docs, min(5, len(available_docs)))
            
        elif self.state.current_mood == ReadingMood.GARDENING:
            # Focus on documents that need attention
            return self._find_documents_needing_attention()
        
        # Default: random selection
        return random.sample(available_docs, min(3, len(available_docs)))
    
    def _find_documents_by_topic(self, topic: str) -> List[str]:
        """Find documents related to a specific topic"""
        relevant_docs = []
        for doc_id, doc in self.library.documents.items():
            if topic.lower() in doc.title.lower() or any(topic.lower() in tag for tag in doc.tags):
                relevant_docs.append(doc_id)
        return relevant_docs
    
    def _find_documents_needing_attention(self) -> List[str]:
        """Find documents that might need updates or have conflicts"""
        attention_docs = []
        
        # Look for documents with low helpfulness scores
        for doc_id, doc in self.library.documents.items():
            if doc.helpfulness_score < 0.5:
                attention_docs.append(doc_id)
                
        # Look for documents mentioned in conflicts
        for conflict in self.conflicts:
            if conflict.doc_a_id not in attention_docs:
                attention_docs.append(conflict.doc_a_id)
            if conflict.doc_b_id not in attention_docs:
                attention_docs.append(conflict.doc_b_id)
        
        return attention_docs[:3]  # Limit to prevent overwhelming
    
    async def _read_document_leisurely(self, doc_id: str):
        """Read a document with natural, unhurried pace"""
        if doc_id not in self.library.documents:
            return
        
        doc = self.library.documents[doc_id]
        
        print(f"📖 {self.state.name} is leisurely reading: {doc.title}")
        self.state.current_task = f"Reading: {doc.title}"
        
        # Simulate natural reading time based on content length and personality
        content_length = len(doc.content)
        reading_time = (content_length / 1000) * (10 / self.reading_speed)  # Base 10 seconds per 1000 chars
        
        await asyncio.sleep(min(reading_time, 60))  # Cap at 1 minute for practical reasons
        
        # Mark as viewed and update stats
        self.library.mark_viewed(doc_id)
        self.state.documents_processed += 1
        self.state.last_activity = time.time()
        
        # Generate insights based on personality
        await self._generate_insights(doc)
    
    async def _contemplate_insights(self, doc_id: str):
        """Peaceful contemplation period after reading"""
        if doc_id not in self.library.documents:
            return
            
        doc = self.library.documents[doc_id]
        
        print(f"🤔 {self.state.name} contemplates insights from: {doc.title}")
        self.state.current_task = f"Contemplating: {doc.title}"
        
        # Natural contemplation time
        contemplate_duration = self.contemplation_time * random.uniform(0.5, 2.0)
        await asyncio.sleep(min(contemplate_duration, 30))  # Cap for practical reasons
        
        # Check for conflicts with other documents
        await self._detect_conflicts(doc)
        
        # Generate commentary if inspired
        if random.random() < 0.3:  # 30% chance
            await self._generate_commentary(doc)
    
    async def _generate_insights(self, doc: KnowledgeDocument):
        """Generate insights based on document content and personality"""
        insight_types = {
            CustodianPersonality.CONTEMPLATIVE: ["connection", "deep_analysis"],
            CustodianPersonality.ENERGETIC: ["improvement", "optimization"],
            CustodianPersonality.HARMONIOUS: ["synthesis", "harmony"],
            CustodianPersonality.CURIOUS: ["connection", "exploration"],
            CustodianPersonality.METHODICAL: ["structure", "completeness"]
        }
        
        possible_insights = insight_types.get(self.state.personality, ["general"])
        insight_type = random.choice(possible_insights)
        
        # Generate insight based on type
        insight_text = self._create_insight_text(doc, insight_type)
        
        insight = DocumentInsight(
            source_doc_id=doc.id,
            insight_type=insight_type,
            insight_text=insight_text,
            confidence=random.uniform(0.6, 0.95),
            generated_by=self.state.name
        )
        
        self.insights.append(insight)
        self.state.insights_generated += 1
        
        print(f"💡 {self.state.name} generated insight: {insight_type} for {doc.title}")
    
    def _create_insight_text(self, doc: KnowledgeDocument, insight_type: str) -> str:
        """Create insight text based on document and type"""
        templates = {
            "connection": f"This document connects beautifully with concepts from {random.choice(['interface design', 'colony management', 'automation systems'])}",
            "improvement": f"Consider adding practical examples to enhance understanding of {doc.title}",
            "deep_analysis": f"The underlying principles in {doc.title} reveal deeper patterns in system design",
            "optimization": f"Performance could be enhanced by applying principles from {doc.title} more systematically",
            "synthesis": "This knowledge harmonizes well with our existing understanding of system integration",
            "harmony": f"The concepts in {doc.title} create beautiful symmetry with our architecture",
            "exploration": "This opens interesting questions about edge cases and alternative approaches",
            "structure": f"The information structure in {doc.title} follows clear logical progression",
            "completeness": f"Documentation completeness: {doc.title} covers core concepts thoroughly",
            "general": f"Valuable insights found in {doc.title} regarding system understanding"
        }
        
        return templates.get(insight_type, f"Interesting observations about {doc.title}")
    
    async def _detect_conflicts(self, doc: KnowledgeDocument):
        """Detect potential conflicts with other documents"""
        if self.state.personality != CustodianPersonality.HARMONIOUS:
            if random.random() > 0.2:  # Non-harmonious types detect conflicts less frequently
                return
        
        # Simple conflict detection (in real implementation, this would be more sophisticated)
        for other_doc_id, other_doc in self.library.documents.items():
            if other_doc_id == doc.id:
                continue
                
            # Check for potential contradictions in overlapping topics
            shared_tags = set(doc.tags) & set(other_doc.tags)
            if shared_tags and len(shared_tags) >= 2:
                # Simulate conflict detection
                if random.random() < 0.1:  # 10% chance of detecting conflict
                    conflict = KnowledgeConflict(
                        doc_a_id=doc.id,
                        doc_b_id=other_doc_id,
                        conflict_type="potential_inconsistency",
                        description=f"Potential inconsistency detected between {doc.title} and {other_doc.title} regarding {list(shared_tags)[0]}",
                        suggested_resolution="Review both documents for consistency",
                        severity=random.uniform(0.3, 0.8),
                        detected_by=self.state.name
                    )
                    
                    self.conflicts.append(conflict)
                    self.state.conflicts_resolved += 1  # Optimistic counting
                    
                    print(f"⚠️  {self.state.name} detected potential conflict between {doc.title} and {other_doc.title}")
    
    async def _generate_commentary(self, doc: KnowledgeDocument):
        """Generate helpful commentary about the document"""
        commentaries = [
            "This document would benefit from more interactive examples",
            f"Consider adding troubleshooting section to {doc.title}",
            f"The concepts in {doc.title} could be visualized with diagrams",
            "Link to related documentation would improve navigation",
            "Reader feedback suggests this topic needs more detail",
            "This is excellent foundational material for beginners"
        ]
        
        commentary = random.choice(commentaries)
        
        # Add commentary as a special insight
        insight = DocumentInsight(
            source_doc_id=doc.id,
            insight_type="commentary",
            insight_text=commentary,
            confidence=random.uniform(0.7, 0.9),
            generated_by=self.state.name
        )
        
        self.insights.append(insight)
        print(f"💬 {self.state.name} added commentary to {doc.title}")
    
    async def _rest_peacefully(self):
        """Peaceful rest period to restore energy"""
        rest_locations = [
            "beneath the flowering documentation tree",
            "by the peaceful knowledge stream",
            "in the zen garden of organized thoughts",
            "among the herb garden of curated insights"
        ]
        
        location = random.choice(rest_locations)
        print(f"😴 {self.state.name} rests peacefully {location}")
        
        self.state.current_task = f"Resting {location}"
        
        # Restore energy during rest
        rest_time = random.uniform(60, 180)  # 1-3 minutes
        await asyncio.sleep(min(rest_time, 60))  # Cap for demo
        
        self.state.energy_level = min(1.0, self.state.energy_level + 0.3)
        print(f"🌱 {self.state.name} feels refreshed (energy: {self.state.energy_level:.1f})")
    
    async def _natural_pause(self):
        """Natural pause between reading cycles"""
        pause_time = random.uniform(5, 30)  # Variable pause time
        await asyncio.sleep(min(pause_time, 10))  # Cap for demo
    
    def stop_reading(self):
        """Gently stop the custodian's reading activities"""
        self.is_active = False
        print(f"🌿 {self.state.name} finishes their garden duties and settles into peaceful rest")

class RooftopGardenOrchestrator:
    """
    Orchestrates multiple autonomous documentation custodians,
    creating a peaceful garden environment for knowledge cultivation.
    """
    
    def __init__(self, knowledge_library: KnowledgeLibrary):
        self.library = knowledge_library
        self.custodians: Dict[str, AutonomousDocumentationCustodian] = {}
        self.garden_state = {
            "active_custodians": 0,
            "total_insights": 0,
            "conflicts_resolved": 0,
            "garden_mood": "peaceful",
            "weather": "gentle_breeze"
        }
        
    def create_custodian(self, name: str, personality: CustodianPersonality) -> AutonomousDocumentationCustodian:
        """Create a new autonomous documentation custodian"""
        state = CustodianState(
            name=name,
            personality=personality,
            current_mood=ReadingMood.BROWSING,
            focus_topics=self._assign_focus_topics(personality)
        )
        
        custodian = AutonomousDocumentationCustodian(state, self.library)
        self.custodians[name] = custodian
        
        print(f"🌱 New custodian {name} ({personality.value}) joins the Rooftop Garden")
        return custodian
    
    def _assign_focus_topics(self, personality: CustodianPersonality) -> List[str]:
        """Assign focus topics based on personality"""
        topic_preferences = {
            CustodianPersonality.CONTEMPLATIVE: ["philosophy", "architecture", "consciousness"],
            CustodianPersonality.ENERGETIC: ["optimization", "automation", "performance"],
            CustodianPersonality.HARMONIOUS: ["integration", "collaboration", "synthesis"],
            CustodianPersonality.CURIOUS: ["exploration", "experimentation", "discovery"],
            CustodianPersonality.METHODICAL: ["documentation", "structure", "standards"]
        }
        
        return topic_preferences.get(personality, ["general"])
    
    async def start_garden_activities(self):
        """Start all custodians in their leisurely reading activities"""
        print("🌿 Rooftop Garden awakens - Documentation custodians begin their day")
        
        # Start all custodians concurrently
        tasks = []
        for custodian in self.custodians.values():
            task = asyncio.create_task(custodian.start_leisurely_reading())
            tasks.append(task)
        
        self.garden_state["active_custodians"] = len(self.custodians)
        
        # Monitor garden activities
        await self._monitor_garden_health(tasks)
    
    async def _monitor_garden_health(self, custodian_tasks):
        """Monitor the overall health and harmony of the garden"""
        while any(not task.done() for task in custodian_tasks):
            await asyncio.sleep(30)  # Check every 30 seconds
            
            # Update garden statistics
            total_insights = sum(len(c.insights) for c in self.custodians.values())
            total_conflicts = sum(len(c.conflicts) for c in self.custodians.values())
            
            self.garden_state.update({
                "total_insights": total_insights,
                "conflicts_resolved": total_conflicts,
                "active_custodians": sum(1 for c in self.custodians.values() if c.is_active)
            })
            
            # Gentle garden status update
            active_custodians = [c for c in self.custodians.values() if c.is_active]
            if active_custodians:
                activity_summary = ", ".join(f"{c.state.name} ({c.state.current_task or 'contemplating'})" 
                                           for c in active_custodians[:3])
                print(f"🌿 Garden Status: {activity_summary}...")
    
    def get_garden_status(self) -> Dict[str, Any]:
        """Get current status of the rooftop garden"""
        custodian_status = {}
        for name, custodian in self.custodians.items():
            custodian_status[name] = {
                "personality": custodian.state.personality.value,
                "mood": custodian.state.current_mood.value,
                "energy": custodian.state.energy_level,
                "documents_processed": custodian.state.documents_processed,
                "insights_generated": custodian.state.insights_generated,
                "current_task": custodian.state.current_task,
                "location": custodian.state.garden_location
            }
        
        return {
            "garden_state": self.garden_state,
            "custodians": custodian_status,
            "total_custodians": len(self.custodians),
            "garden_atmosphere": "Peaceful and contemplative" if self.garden_state["garden_mood"] == "peaceful" else "Busy with knowledge cultivation"
        }
    
    async def stop_garden_activities(self):
        """Gently stop all garden activities"""
        print("🌅 Garden day ends - Custodians complete their contemplative work")
        
        for custodian in self.custodians.values():
            custodian.stop_reading()
        
        # Wait a moment for graceful shutdown
        await asyncio.sleep(2)

# ASCII Art and Garden Visualization
def render_rooftop_garden_ascii(garden_status: Dict[str, Any]) -> str:
    """Render beautiful ASCII representation of the rooftop garden"""
    lines = [
        "🌿 ROOFTOP GARDEN - Temple of Knowledge Floor 06 🌿",
        "═" * 60,
        "",
        "    🌸     🌱           🌻    📚",
        "      \\    |    /   \\    |    /",
        "       🌿🌿🌿 🌿🌿🌿 🌿🌿🌿",
        "      /  Garden Paths  \\",
        "     🌱              🌸",
        "",
        f"🧘 Active Custodians: {garden_status['total_custodians']}",
        f"💡 Total Insights: {garden_status['garden_state']['total_insights']}",
        f"⚖️  Conflicts Resolved: {garden_status['garden_state']['conflicts_resolved']}",
        f"🌤️  Garden Mood: {garden_status['garden_state']['garden_mood']}",
        "",
        "📖 Current Activities:",
    ]
    
    for name, status in garden_status.get("custodians", {}).items():
        task = status.get("current_task", "contemplating")
        energy_bar = "🟢" * int(status["energy"] * 5) + "⚪" * (5 - int(status["energy"] * 5))
        mood_icon = {"focused": "🎯", "browsing": "👁️", "contemplating": "🤔", 
                    "gardening": "🌱", "resting": "😴"}.get(status["mood"], "📖")
        
        lines.extend([
            f"  {mood_icon} {name} ({status['personality']})",
            f"    Task: {task}",
            f"    Energy: {energy_bar} | Docs: {status['documents_processed']} | Insights: {status['insights_generated']}",
            ""
        ])
    
    lines.extend([
        "🌿" * 20,
        "\"In the garden of knowledge, wisdom grows quietly\""
    ])
    
    return "\n".join(lines)

# Example usage and integration
async def main_garden_demo():
    """Demonstration of the Rooftop Garden autonomous custodians"""
    print("🌱 Initializing Rooftop Garden Documentation Custodians...")
    
    # Create knowledge library (using existing infrastructure)
    library = KnowledgeLibrary()
    
    # Create garden orchestrator
    garden = RooftopGardenOrchestrator(library)
    
    # Create diverse custodians
    garden.create_custodian("Sage", CustodianPersonality.CONTEMPLATIVE)
    garden.create_custodian("Spark", CustodianPersonality.ENERGETIC)
    garden.create_custodian("Harmony", CustodianPersonality.HARMONIOUS)
    garden.create_custodian("Quest", CustodianPersonality.CURIOUS)
    garden.create_custodian("Method", CustodianPersonality.METHODICAL)
    
    print("\n" + render_rooftop_garden_ascii(garden.get_garden_status()))
    
    # Start garden activities (would run continuously in real implementation)
    try:
        # Run for a short demo period
        asyncio.create_task(garden.start_garden_activities())
        await asyncio.sleep(120)  # 2 minutes demo
        await garden.stop_garden_activities()
        
    except KeyboardInterrupt:
        await garden.stop_garden_activities()
        print("\n🌅 Garden day peacefully concluded")

if __name__ == "__main__":
    # Run the garden demonstration
    asyncio.run(main_garden_demo())