apiVersion: 1

datasources:
  - name: Timescale
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    user: nusyq
    secureJsonData:
      password: ${TIMESCALE_PASSWORD}
    jsonData:
      database: consciousness
      postgresVersion: 1500
      sslmode: disable
      timescaledb: true

  - name: Postgres Core
    type: postgres
    access: proxy
    url: host.docker.internal:5433
    user: nusyq
    secureJsonData:
      password: ${POSTGRES_CORE_PASSWORD}
    jsonData:
      database: nusyq_core
      postgresVersion: 1500
      sslmode: disable
