# Terminal Watcher for chatgpt_bridge
# Auto-generated by activate_live_terminal_routing.py

$repoRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$logDir = Join-Path $repoRoot "data\terminal_logs"
$primaryLogFile = Join-Path $logDir "chatgpt_bridge.log"
$terminalName = "chatgpt_bridge"
$sourceLog = $primaryLogFile
$sourceLabel = "NuSyQ terminal log"
$fallbackLogs = @()

if ($terminalName -eq "copilot") {
    $logsRoot = Join-Path $env:APPDATA "Code\logs"
    if (Test-Path $logsRoot) {
        $copilotCandidates = Get-ChildItem -Path $logsRoot -Filter "GitHub Copilot Chat.log" -Recurse -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending
        if ($copilotCandidates) {
            $sourceLog = $copilotCandidates[0].FullName
            $sourceLabel = "VS Code Copilot Chat log"
        }
    }
}

if (($sourceLog -eq $primaryLogFile) -and (!(Test-Path $sourceLog))) {
    foreach ($fallback in $fallbackLogs) {
        if (![string]::IsNullOrWhiteSpace($fallback) -and (Test-Path $fallback)) {
            $sourceLog = $fallback
            $sourceLabel = "NuSyQ legacy terminal log"
            break
        }
    }
}

Write-Host "=== $terminalName Terminal - Live Output ===" -ForegroundColor Cyan
Write-Host "Source: $sourceLabel" -ForegroundColor Gray
Write-Host "Watching: $sourceLog" -ForegroundColor Gray
if ($sourceLog -ne $primaryLogFile) {
    Write-Host "Mirror destination: $primaryLogFile" -ForegroundColor DarkGray
}
Write-Host ""

# Ensure destination log exists
if (!(Test-Path $primaryLogFile)) {
    New-Item -ItemType File -Path $primaryLogFile -Force | Out-Null
    Write-Host "Created log file: $primaryLogFile" -ForegroundColor Yellow
}

if (!(Test-Path $sourceLog)) {
    Write-Host "Source log not found: $sourceLog" -ForegroundColor Red
    Write-Host "Tip: open VS Code Copilot chat once, then relaunch this watcher." -ForegroundColor Yellow
    exit 1
}

# Tail the log file and format output
Get-Content $sourceLog -Wait -Tail 20 | ForEach-Object {
    $line = $_
    if ($null -eq $line) {
        return
    }

    $trimmed = $line.Trim()
    if ($trimmed.Length -eq 0) {
        return
    }

    $entry = $null
    if ($trimmed.StartsWith("{") -and $trimmed.EndsWith("}")) {
        try {
            $entry = $trimmed | ConvertFrom-Json -ErrorAction Stop
        } catch {
            $entry = $null
        }
    }

        if ($null -ne $entry) {
        $timestamp = $entry.timestamp
        $level = $entry.level
        $message = $entry.message
        if ($null -ne $message) {
            $message = "$message"
            $message = ($message -replace '[^\x00-\x7F]', '?')
        }

        # Color based on level
        $color = switch ($level) {
            "ERROR" { "Red" }
            "WARNING" { "Yellow" }
            "INFO" { "White" }
            "DEBUG" { "Gray" }
            default { "White" }
        }

        Write-Host "[$timestamp] " -NoNewline -ForegroundColor Gray
        Write-Host "[$level] " -NoNewline -ForegroundColor $color
        Write-Host $message -ForegroundColor $color

        if ($sourceLog -ne $primaryLogFile) {
            Add-Content -Path $primaryLogFile -Value $trimmed -Encoding UTF8 -ErrorAction SilentlyContinue
        }
    } else {
        # If not JSON, print as plain text but mirror as NDJSON for tooling.
        $safeLine = ($line -replace '[^\x00-\x7F]', '?')
        Write-Host $safeLine -ForegroundColor White
        if ($sourceLog -ne $primaryLogFile) {
            $mirrorEntry = @{
                timestamp = (Get-Date).ToString("o")
                level = "INFO"
                source = $terminalName
                message = $safeLine
            } | ConvertTo-Json -Compress
            Add-Content -Path $primaryLogFile -Value $mirrorEntry -Encoding UTF8 -ErrorAction SilentlyContinue
        }
    }
}
