# Terminal Watcher for copilot
# Auto-generated by activate_live_terminal_routing.py

$repoRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$logDir = Join-Path $repoRoot "data\terminal_logs"
$primaryLogFile = Join-Path $logDir "copilot.log"
$terminalName = "copilot"
$sourceLogs = @($primaryLogFile)
$sourceLabel = "NuSyQ terminal log"

if ($terminalName -eq "copilot") {
    $logsRoot = Join-Path $env:APPDATA "Code\logs"
    if (Test-Path $logsRoot) {
        $copilotCandidates = Get-ChildItem -Path $logsRoot -Filter "GitHub Copilot Chat.log" -Recurse -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending
        if ($copilotCandidates) {
            $sourceLogs += $copilotCandidates[0].FullName
            $sourceLabel = "VS Code Copilot Chat log + NuSyQ Copilot log"
        }
    }
}

Write-Host "=== $terminalName Terminal - Live Output ===" -ForegroundColor Cyan
Write-Host "Source: $sourceLabel" -ForegroundColor Gray
Write-Host "Watching: $([string]::Join(', ', $sourceLogs))" -ForegroundColor Gray
Write-Host ""

# Ensure destination log exists
if (!(Test-Path $primaryLogFile)) {
    New-Item -ItemType File -Path $primaryLogFile -Force | Out-Null
    Write-Host "Created log file: $primaryLogFile" -ForegroundColor Yellow
}

# Ensure at least one source log exists
$existingSources = $sourceLogs | Where-Object { Test-Path $_ }
if (-not $existingSources) {
    Write-Host "None of the expected source logs exist: $([string]::Join(', ', $sourceLogs))" -ForegroundColor Red
    Write-Host "Tip: open VS Code Copilot chat once, then relaunch this watcher." -ForegroundColor Yellow
    exit 1
}

# Tail the log files and format output
Get-Content $existingSources -Wait -Tail 20 | ForEach-Object {
    $line = $_
    if ($null -eq $line) {
        return
    }

    $trimmed = $line.Trim()
    if ($trimmed.Length -eq 0) {
        return
    }

    $entry = $null
    if ($trimmed.StartsWith("{") -and $trimmed.EndsWith("}")) {
        try {
            $entry = $trimmed | ConvertFrom-Json -ErrorAction Stop
        } catch {
            $entry = $null
        }
    }

        if ($null -ne $entry) {
        $timestamp = $entry.timestamp
        $level = $entry.level
        $message = $entry.message
        if ($null -ne $message) {
            $message = "$message"
            $message = ($message -replace '[^\x00-\x7F]', '?')
        }

        # Color based on level
        $color = switch ($level) {
            "ERROR" { "Red" }
            "WARNING" { "Yellow" }
            "INFO" { "White" }
            "DEBUG" { "Gray" }
            default { "White" }
        }

        Write-Host "[$timestamp] " -NoNewline -ForegroundColor Gray
        Write-Host "[$level] " -NoNewline -ForegroundColor $color
        Write-Host $message -ForegroundColor $color

    } else {
        # If not JSON, print as plain text.
        $safeLine = ($line -replace '[^\x00-\x7F]', '?')
        Write-Host $safeLine -ForegroundColor White
    }
}
