"""Doctrine Checker — Validates system implementation against architectural doctrine.

Compares .instructions.md files and docs/doctrine/ against git commit history
to identify drift, violations, and compliance gaps.
"""

import logging
import re
import subprocess
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class DoctrineViolation:
    """A specific violation of architectural doctrine."""

    mandate: str  # The doctrinal requirement
    violation_type: str  # "missing_implementation" | "forbidden_pattern" | "drift" | "abandoned"
    evidence: list[str]  # File paths, commit SHAs, grep results
    severity: str  # "critical" | "high" | "medium" | "low"
    recommendation: str  # What to do about it
    source_file: str | None = None  # Which instruction file defines this


@dataclass
class ComplianceReport:
    """Overall doctrine compliance assessment."""

    timestamp: str
    hub_path: Path
    total_mandates: int = 0
    violations: list[DoctrineViolation] = field(default_factory=list)
    compliance_score: float = 0.0  # 0.0 - 1.0
    instruction_files_parsed: list[str] = field(default_factory=list)
    doctrine_files_parsed: list[str] = field(default_factory=list)
    git_commits_analyzed: int = 0
    insights: list[str] = field(default_factory=list)

    def to_markdown(self) -> str:
        """Generate markdown compliance report."""
        lines = []
        lines.append("# Doctrine Compliance Report\n")
        lines.append(f"**Generated**: {self.timestamp}\n")
        lines.append(f"**Compliance Score**: {self.compliance_score:.1%}\n")
        lines.append(f"**Total Mandates**: {self.total_mandates}\n")
        lines.append(f"**Violations**: {len(self.violations)}\n")
        lines.append(f"**Commits Analyzed**: {self.git_commits_analyzed}\n\n")

        # Files analyzed
        lines.append("## Files Analyzed\n")
        lines.append(f"**Instructions**: {len(self.instruction_files_parsed)} files\n")
        for f in self.instruction_files_parsed[:5]:
            lines.append(f"  - {Path(f).name}\n")
        if len(self.instruction_files_parsed) > 5:
            lines.append(f"  - ...and {len(self.instruction_files_parsed) - 5} more\n")

        lines.append(f"\n**Doctrine**: {len(self.doctrine_files_parsed)} files\n")
        for f in self.doctrine_files_parsed:
            lines.append(f"  - {Path(f).name}\n")

        # Violations by severity
        if self.violations:
            lines.append("\n## Violations by Severity\n")
            for severity in ["critical", "high", "medium", "low"]:
                sevs = [v for v in self.violations if v.severity == severity]
                if sevs:
                    lines.append(f"\n### {severity.upper()} ({len(sevs)})\n")
                    for v in sevs[:10]:  # Max 10 per severity
                        lines.append(f"\n#### {v.mandate}\n")
                        lines.append(f"- **Type**: {v.violation_type}\n")
                        if v.source_file:
                            lines.append(f"- **Source**: {Path(v.source_file).name}\n")
                        lines.append("- **Evidence**:\n")
                        for e in v.evidence[:3]:
                            lines.append(f"  - {e}\n")
                        if len(v.evidence) > 3:
                            lines.append(f"  - ...and {len(v.evidence) - 3} more\n")
                        lines.append(f"- **Recommendation**: {v.recommendation}\n")

        # Insights
        if self.insights:
            lines.append("\n## Insights\n")
            for insight in self.insights:
                lines.append(f"- {insight}\n")

        lines.append(f"\n---\n*Generated by DoctrineChecker at {self.timestamp}*\n")
        return "".join(lines)


class DoctrineChecker:
    """Validates system implementation against architectural doctrine."""

    def __init__(self, hub_path: Path) -> None:
        """Initialize DoctrineChecker with hub_path."""
        self.hub_path = hub_path
        self.instructions_dir = hub_path / ".github" / "instructions"
        self.doctrine_dir = hub_path / "docs" / "doctrine"

    def check_compliance(self, commits_to_analyze: int = 50) -> ComplianceReport:
        """Generate comprehensive compliance report.

        Args:
            commits_to_analyze: Number of recent commits to analyze

        Returns:
            ComplianceReport with violations and recommendations
        """
        report = ComplianceReport(
            timestamp=datetime.now().isoformat(),
            hub_path=self.hub_path,
        )

        # Parse instruction files
        instruction_files = list(self.instructions_dir.glob("*.instructions.md"))
        for f in instruction_files:
            report.instruction_files_parsed.append(str(f))

        # Parse doctrine files
        doctrine_files = list(self.doctrine_dir.glob("*.md"))
        for f in doctrine_files:
            report.doctrine_files_parsed.append(str(f))

        # Analyze git commits
        commits = self._get_recent_commits(commits_to_analyze)
        report.git_commits_analyzed = len(commits)

        # Check FILE_PRESERVATION_MANDATE compliance
        self._check_file_preservation(report)

        # Check for circular imports
        self._check_circular_imports(report)

        # Check for blocking operations
        self._check_blocking_operations(report)

        # Check mandatory files
        self._check_mandatory_files(report)

        # Check for abandoned code
        self._check_abandoned_code(report, commits)

        # Check receipt discipline
        self._check_receipt_discipline(report, commits)

        # Calculate compliance score
        report.total_mandates = 6  # Number of checks above
        violations_count = len(report.violations)
        report.compliance_score = max(0.0, 1.0 - (violations_count * 0.15))

        # Generate insights
        self._generate_insights(report)

        return report

    def _get_recent_commits(self, count: int) -> list[dict[str, Any]]:
        """Get recent git commits with metadata."""
        try:
            result = subprocess.run(
                [
                    "git",
                    "log",
                    f"-{count}",
                    "--oneline",
                    "--format=%H|%s|%ad",
                    "--date=iso",
                ],
                cwd=self.hub_path,
                capture_output=True,
                text=True,
                check=False,
                timeout=30,
            )
            if result.returncode != 0:
                return []

            commits = []
            for line in result.stdout.strip().split("\n"):
                if not line:
                    continue
                parts = line.split("|", 2)
                if len(parts) == 3:
                    commits.append({"sha": parts[0], "message": parts[1], "date": parts[2]})
            return commits
        except Exception:
            return []

    def _check_file_preservation(self, report: ComplianceReport) -> None:
        """Check for FILE_PRESERVATION_MANDATE violations."""
        # Look for new_* files when original exists
        try:
            result = subprocess.run(
                ["find", "src/", "-name", "new_*.py"],
                cwd=self.hub_path,
                capture_output=True,
                text=True,
                check=False,
                timeout=10,
            )
            new_files = [f for f in result.stdout.strip().split("\n") if f]

            for new_file in new_files:
                # Check if base file exists
                base_name = new_file.replace("new_", "")
                base_path = self.hub_path / base_name
                if base_path.exists():
                    report.violations.append(
                        DoctrineViolation(
                            mandate="Edit-First, Create-Last (FILE_PRESERVATION_MANDATE)",
                            violation_type="forbidden_pattern",
                            evidence=[f"Found {new_file} when {base_name} exists"],
                            severity="high",
                            recommendation=f"Merge {new_file} into {base_name} and delete {new_file}",
                            source_file=str(
                                self.instructions_dir / "FILE_PRESERVATION_MANDATE.instructions.md"
                            ),
                        )
                    )
        except Exception:
            logger.debug("Suppressed Exception", exc_info=True)

    def _check_circular_imports(self, report: ComplianceReport) -> None:
        """Check for circular import violations."""
        try:
            result = subprocess.run(
                ["grep", "-r", "from src.orchestration import", "src/"],
                cwd=self.hub_path,
                capture_output=True,
                text=True,
                check=False,
                timeout=10,
            )
            if result.returncode == 0 and result.stdout:
                matches = result.stdout.strip().split("\n")
                if len(matches) > 2:  # Allow a few, flag if excessive
                    report.violations.append(
                        DoctrineViolation(
                            mandate="Avoid circular imports (Doctrine)",
                            violation_type="drift",
                            evidence=[
                                f"Found {len(matches)} direct imports of src.orchestration",
                                *matches[:3],
                            ],
                            severity="medium",
                            recommendation="Refactor to use dependency injection or move shared code to utils",
                            source_file=None,
                        )
                    )
        except Exception:
            logger.debug("Suppressed Exception", exc_info=True)

    def _check_blocking_operations(self, report: ComplianceReport) -> None:
        """Check for blocking operations like infinite loops."""
        try:
            result = subprocess.run(
                ["grep", "-r", "while True", "src/"],
                cwd=self.hub_path,
                capture_output=True,
                text=True,
                check=False,
                timeout=10,
            )
            if result.returncode == 0 and result.stdout:
                matches = [m for m in result.stdout.strip().split("\n") if "test" not in m.lower()]
                if len(matches) > 10:  # Flag if excessive
                    report.violations.append(
                        DoctrineViolation(
                            mandate="Avoid blocking operations (Doctrine)",
                            violation_type="drift",
                            evidence=[
                                f"Found {len(matches)} 'while True' loops in src/",
                                *matches[:3],
                            ],
                            severity="low",
                            recommendation="Convert to async generators or add iteration limits",
                            source_file=None,
                        )
                    )
        except Exception:
            logger.debug("Suppressed Exception", exc_info=True)

    def _check_mandatory_files(self, report: ComplianceReport) -> None:
        """Check that mandatory files exist."""
        mandatory = [
            "src/main.py",
            "src/orchestration/",
            "src/healing/",
            "src/diagnostics/",
            "config/action_catalog.json",
            "scripts/start_nusyq.py",
            "AGENTS.md",
            "docs/doctrine/SYSTEM_OVERVIEW.md",
        ]

        missing = []
        for f in mandatory:
            path = self.hub_path / f
            if not path.exists():
                missing.append(f)

        if missing:
            report.violations.append(
                DoctrineViolation(
                    mandate="Preserve mandatory files (FILE_PRESERVATION_MANDATE)",
                    violation_type="missing_implementation",
                    evidence=[f"Missing: {', '.join(missing)}"],
                    severity="critical",
                    recommendation=f"Restore missing files: {', '.join(missing)}",
                    source_file=str(
                        self.instructions_dir / "FILE_PRESERVATION_MANDATE.instructions.md"
                    ),
                )
            )

    def _check_abandoned_code(
        self, report: ComplianceReport, _commits: list[dict[str, Any]]
    ) -> None:
        """Check for abandoned code markers."""
        try:
            result = subprocess.run(
                ["grep", "-r", "TODO\\|TODO\\|DEPRECATED", "src/", "--include=*.py"],
                cwd=self.hub_path,
                capture_output=True,
                text=True,
                check=False,
                timeout=10,
            )
            if result.returncode == 0 and result.stdout:
                markers = result.stdout.strip().split("\n")
                if len(markers) > 20:  # Flag if excessive
                    report.violations.append(
                        DoctrineViolation(
                            mandate="Clean up abandoned code (FILE_PRESERVATION_MANDATE)",
                            violation_type="abandoned",
                            evidence=[
                                f"Found {len(markers)} TODO/TODO/DEPRECATED markers",
                                *markers[:5],
                            ],
                            severity="low",
                            recommendation="Run cleanup: review and remove or implement TODOs older than 90 days",
                            source_file=str(
                                self.instructions_dir / "FILE_PRESERVATION_MANDATE.instructions.md"
                            ),
                        )
                    )
        except Exception:
            logger.debug("Suppressed Exception", exc_info=True)

    def _check_receipt_discipline(
        self, report: ComplianceReport, commits: list[dict[str, Any]]
    ) -> None:
        """Check if commits follow receipt discipline (conventional commits)."""
        non_conventional = []
        for commit in commits[:20]:  # Check last 20
            msg = commit["message"]
            # Check for conventional commit format: type(scope): message
            if not re.match(
                r"^(feat|fix|docs|chore|refactor|test|style|perf|ci|build)\(", msg
            ) and not re.match(r"^(feat|fix|docs|chore|refactor|test|style|perf|ci|build): ", msg):
                non_conventional.append(f"{commit['sha'][:7]}: {msg[:60]}")

        if len(non_conventional) > 5:
            report.violations.append(
                DoctrineViolation(
                    mandate="Receipt discipline: conventional commits (MEGA_THROUGHPUT_OPERATOR_MODE)",
                    violation_type="drift",
                    evidence=[
                        f"Found {len(non_conventional)} non-conventional commits",
                        *non_conventional[:3],
                    ],
                    severity="low",
                    recommendation="Use conventional commit format: type(scope): message",
                    source_file=str(
                        self.instructions_dir / "MEGA_THROUGHPUT_OPERATOR_MODE.instructions.md"
                    ),
                )
            )

    def _generate_insights(self, report: ComplianceReport) -> None:
        """Generate actionable insights from violations."""
        if report.compliance_score >= 0.9:
            report.insights.append(f"✅ Excellent compliance ({report.compliance_score:.1%})")
        elif report.compliance_score >= 0.7:
            report.insights.append(
                f"⚠️  Good compliance ({report.compliance_score:.1%}) with room for improvement"
            )
        else:
            report.insights.append(
                f"❌ Low compliance ({report.compliance_score:.1%}) - immediate action needed"
            )

        # Count by severity
        critical = len([v for v in report.violations if v.severity == "critical"])
        high = len([v for v in report.violations if v.severity == "high"])
        medium = len([v for v in report.violations if v.severity == "medium"])
        low = len([v for v in report.violations if v.severity == "low"])

        if critical > 0:
            report.insights.append(f"🔴 {critical} CRITICAL violations require immediate attention")
        if high > 0:
            report.insights.append(f"🟠 {high} HIGH priority violations found")
        if medium > 0:
            report.insights.append(f"🟡 {medium} MEDIUM priority items for next sprint")
        if low > 0:
            report.insights.append(f"🔵 {low} LOW priority technical debt items")

        # Insight: Most common violation type
        if report.violations:
            violation_types: dict[str, int] = {}
            for v in report.violations:
                violation_types[v.violation_type] = violation_types.get(v.violation_type, 0) + 1
            most_common = max(violation_types.items(), key=lambda x: x[1])
            report.insights.append(
                f"Most common issue: {most_common[0]} ({most_common[1]} occurrences)"
            )
