#!/usr/bin/env tsx
import { mkdirSync, renameSync, statSync } from "node:fs";
import { join } from "node:path";
import { readdirSync } from "node:fs";

const ROOT = ".";
const OUT = "attic/quarantine";           // anneal, don't delete
const MAX_TXT_MB = +(process.env.MAX_TXT_MB || "2"); // text files bigger than this → attic
const SPAM_HINTS = [
  "autogenerated","dump","stacktrace","minified","minify","bundle",
  "report-", "artifact-", "999999", "placeholder", "lorem"
];

const SKIP_DIRS = new Set(["node_modules",".git","dist","build",".next",".cache","coverage","models","ollama"]);
const TEXT_RX = /\.(md|rtf|txt|log|out)$/i;

function* walk(d:string): Generator<string> {
  for (const e of readdirSync(d)) {
    if (SKIP_DIRS.has(e)) continue;
    const p = join(d,e);
    try {
      const s = statSync(p);
      if (s.isDirectory()) yield* walk(p);
      else yield p;
    } catch {}
  }
}

function isSpammy(file:string){ const f=file.toLowerCase(); return SPAM_HINTS.some(h=>f.includes(h)); }

let moved=0, bytes=0;
mkdirSync(OUT, { recursive: true });

for (const f of walk(ROOT)) {
  const s = statSync(f);
  const isText = TEXT_RX.test(f);
  const over = (s.size/1e6) > MAX_TXT_MB;
  if ((isText && over) || isSpammy(f)) {
    const dest = join(OUT, f.replace(/[\/\\:]/g,"__"));
    try { renameSync(f, dest); moved++; bytes += s.size; }
    catch (e) { /* best effort */ }
  }
}
console.log(`[quarantine] moved=${moved} totalMB=${(bytes/1e6).toFixed(2)} → ${OUT}`);