"""TaskManager - ChatDev-generated CLI task management tool.

Generated by ChatDev with Ollama backend (qwen2.5-coder:7b).
Graduated from testing_chamber/staging on 2026-03-01.

Usage:
    python -m src.tools.task_manager.main add "Task description"
    python -m src.tools.task_manager.main list
    python -m src.tools.task_manager.main delete <id>

This module demonstrates:
1. ChatDev + Ollama integration (no OpenAI required)
2. Multi-file project generation
3. Testing chamber graduation workflow
"""

from src.tools.task_manager.commands import add_task, delete_task, list_tasks
from src.tools.task_manager.storage import load_tasks, save_tasks

__all__ = ["add_task", "delete_task", "list_tasks", "load_tasks", "save_tasks"]
