#!/usr/bin/env python3
"""Module containing task management functions.

Generated by ChatDev + Ollama (qwen2.5-coder:7b).
"""

import logging

from .storage import load_tasks, save_tasks

logger = logging.getLogger(__name__)

# Load tasks on module import
tasks = load_tasks()


def add_task(task):
    """Add a new task to the list."""
    tasks.append({"id": len(tasks) + 1, "description": task})
    save_tasks(tasks)
    logger.info(f"Task added: {task}")


def list_tasks():
    """List all tasks."""
    if not tasks:
        logger.info("No tasks found.")
    else:
        for task in tasks:
            logger.info(f"{task['id']}: {task['description']}")


def delete_task(task_id):
    """Delete a task by ID."""
    global tasks
    tasks = [t for t in tasks if t["id"] != task_id]
    save_tasks(tasks)
    logger.info(f"Task {task_id} deleted.")
