#!/usr/bin/env python3
"""Task Manager CLI - Main entry point.

Generated by ChatDev + Ollama (qwen2.5-coder:7b).
"""

import argparse

from .commands import add_task, delete_task, list_tasks


def main():
    parser = argparse.ArgumentParser(description="Task Manager CLI Tool")
    subparsers = parser.add_subparsers(dest="command")

    # Add task command
    add_parser = subparsers.add_parser("add", help="Add a new task")
    add_parser.add_argument("task", type=str, help="Description of the task")

    # List tasks command
    subparsers.add_parser("list", help="List all tasks")

    # Delete task command
    delete_parser = subparsers.add_parser("delete", help="Delete a task")
    delete_parser.add_argument("task_id", type=int, help="ID of the task to delete")

    args = parser.parse_args()

    if args.command == "add":
        add_task(args.task)
    elif args.command == "list":
        list_tasks()
    elif args.command == "delete":
        delete_task(args.task_id)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
