"""NuSyQ-Hub module: code_metrics.

Core system module for the NuSyQ-Hub ecosystem.

Location: analysis/code_metrics
Parent: analysis > code_metrics

This module is spine-wired. See src/spine/module_registry.json
for centralized configuration and public API definition.
"""

# Auto-generated by scripts/generate_missing_inits.py
# To add public API, update src/spine/module_registry.json

__all__: list[str] = []
