#!/usr/bin/env python3
"""
agents/documenter.py — Documentation Generator Agent

Generates man pages for game commands, lore pages for agents/NPCs,
and developer documentation for major systems. Uses LLM when available,
falls back to deterministic templates otherwise.

Usage:
    python3 agents/documenter.py                     # document everything new
    python3 agents/documenter.py --man <cmd>         # generate one man page
    python3 agents/documenter.py --lore <agent_id>   # generate one lore page
    python3 agents/documenter.py --audit             # list missing docs
    python3 agents/documenter.py --dev               # generate dev system docs
    python3 agents/documenter.py --all               # regenerate all
    python3 agents/documenter.py --task <id>         # run for orchestrator task
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.request
from pathlib import Path
from typing import Optional

BASE_DIR = Path(__file__).parent.parent
DOCS_DIR = BASE_DIR / "docs"
MAN_DIR = DOCS_DIR / "commands"
LORE_DIR = DOCS_DIR / "lore"
DEV_DIR = DOCS_DIR / "development"
BASE_URL = "http://localhost:8008"

for d in (MAN_DIR, LORE_DIR, DEV_DIR):
    d.mkdir(parents=True, exist_ok=True)


def log(level: str, msg: str, **ctx):
    ts = time.strftime("%H:%M:%S")
    colors = {"INFO": "\033[36m", "OK": "\033[32m", "WARN": "\033[33m",
              "ERROR": "\033[31m", "GEN": "\033[35m"}
    c = colors.get(level, "\033[0m")
    r = "\033[0m"
    kv = "  ".join(f"{k}={v}" for k, v in ctx.items())
    print(f"{c}[{level}]{r} {ts} {msg}" + (f"  | {kv}" if kv else ""))


def _post(path: str, data: dict) -> dict:
    try:
        req = urllib.request.Request(
            BASE_URL + path, json.dumps(data).encode(),
            headers={"Content-Type": "application/json"}, method="POST",
        )
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read())
    except Exception as e:
        return {"error": str(e)}


def _get(path: str) -> dict:
    try:
        with urllib.request.urlopen(BASE_URL + path, timeout=8) as r:
            return json.loads(r.read())
    except Exception as e:
        return {"error": str(e)}


def _llm_generate(prompt: str, max_tokens: int = 400) -> Optional[str]:
    result = _post("/api/llm/generate", {"prompt": prompt, "max_tokens": max_tokens, "temperature": 0.5})
    if "error" not in result and result.get("text"):
        return result["text"].strip()
    return None


def _man_template(cmd: str, synopsis: str, description: str, options: list[str], examples: list[str]) -> str:
    opt_block = "\n".join(f"  {o}" for o in options) if options else "  (none)"
    ex_block = "\n".join(f"  {e}" for e in examples) if examples else "  (none)"
    return f"""# {cmd.upper()}(1) — Terminal Depths Man Page

## NAME
  {cmd} — {synopsis}

## SYNOPSIS
  {cmd} [OPTIONS] [ARGS]

## DESCRIPTION
{description}

## OPTIONS
{opt_block}

## EXAMPLES
{ex_block}

## ENVIRONMENT
  Terminal Depths v1.0 — cyberpunk hacking simulation

## SEE ALSO
  help, man, commands

---
*Generated by agents/documenter.py on {time.strftime("%Y-%m-%d")}*
"""


def _lore_template(agent_id: str, name: str, faction: str, role: str, lore: str) -> str:
    return f"""# {name} — Agent Dossier

**ID:** `{agent_id}`
**Faction:** {faction}
**Role:** {role}

## Background
{lore}

## Known Operations
*[CLASSIFIED — clearance level 4 required]*

## Communication Protocol
Contact via terminal command: `agents` → select {name}

---
*Dossier compiled: {time.strftime("%Y-%m-%d")} | Classification: RESTRICTED*
"""


# ── Known command metadata for template generation ─────────────────────────
_COMMAND_META: dict = {
    "ls": ("list directory contents", "List files and directories in a given path.",
           ["-l  long format with permissions", "-a  show hidden files", "-h  human-readable sizes"],
           ["ls /home/ghost", "ls -la /opt", "ls -lh /var/log"]),
    "cat": ("concatenate and print files", "Print the contents of one or more files.",
            ["-n  number output lines", "-A  show non-printing chars"],
            ["cat /etc/passwd", "cat readme.txt", "cat file1 file2"]),
    "grep": ("search for patterns in files", "Search input for lines matching a pattern.",
             ["-i  case insensitive", "-r  recursive search", "-n  show line numbers", "-v  invert match"],
             ["grep 'password' /etc/config", "grep -ri 'chimera' /opt", "grep -n 'error' app.log"]),
    "find": ("search for files", "Walk the filesystem tree finding files matching criteria.",
             ["-name  match by filename", "-type f  files only", "-type d  directories only", "-size +1k  size filter"],
             ["find /home -name '*.sh'", "find / -type f -name 'flag*'", "find /opt -size +10k"]),
    "ps": ("report process status", "Display information about active processes.",
           ["-aux  all processes with details", "-ef  full format listing"],
           ["ps aux", "ps -ef | grep root"]),
    "nmap": ("network mapper", "Scan network hosts and open ports.",
             ["-sS  TCP SYN scan", "-sT  TCP connect scan", "-p  port range", "-A  aggressive scan"],
             ["nmap 192.168.1.0/24", "nmap -sS -p 22,80,443 target", "nmap -A 10.0.0.1"]),
    "ssh": ("secure shell client", "Connect to a remote server over encrypted channel.",
            ["-i key  use identity file", "-p port  custom port", "-L  local port forward"],
            ["ssh ghost@nexus-corp.local", "ssh -i id_rsa root@dark-node", "ssh -p 2222 user@host"]),
    "sudo": ("execute as superuser", "Run a command with elevated privileges.",
             ["sudo <command>  run as root", "sudo -l  list available commands"],
             ["sudo find / -name 'flag'", "sudo cat /etc/shadow"]),
    "exploit": ("run exploit module", "Execute a preloaded exploit against a target.",
                ["--target <host>  specify target", "--module <name>  exploit module", "--payload <name>  payload type"],
                ["exploit --target nexus-core", "exploit --module ms17_010 --target 10.0.0.5"]),
    "scan": ("scan target for vulnerabilities", "Run a vulnerability assessment against a host.",
             ["--full  comprehensive scan", "--quiet  suppress verbose output"],
             ["scan nexus-corp.local", "scan --full 10.0.0.0/24"]),
    "hack": ("attempt system intrusion", "Launch an intrusion sequence against a target node.",
             ["--stealth  avoid detection", "--brute  enable brute force"],
             ["hack dark-node-7", "hack --stealth nexus-control"]),
    "signal": ("send ARG signal", "Transmit a signal code to awaken hidden narrative elements.",
               ["3.14159  wake ZERO", "0x5343  contact Special Circumstances", "0x44  contact Daedalus"],
               ["signal 3.14159", "signal 0x5343"]),
    "agents": ("list active agents", "Display the agent roster with trust scores and faction data.",
               ["(no options — displays interactive roster)"],
               ["agents"]),
    "faction": ("show faction status", "Display your standing with all major factions.",
                ["(no options — shows all factions)"],
                ["faction"]),
    "trust": ("query trust matrix", "View trust, respect, and fear scores for an agent.",
              ["<agent_id>  query specific agent"],
              ["trust raven", "trust ada"]),
    "man": ("display manual page", "Show the manual page for a command.",
            ["<command>  command to look up"],
            ["man ls", "man nmap", "man exploit"]),
}


class Documenter:
    def __init__(self):
        self.generated = 0
        self.skipped = 0
        self.errors = 0

    def _write_doc(self, path: Path, content: str, force: bool = False) -> bool:
        if path.exists() and not force:
            self.skipped += 1
            return False
        path.write_text(content)
        self.generated += 1
        log("GEN", f"Written: {path.relative_to(BASE_DIR)}")
        return True

    def generate_man_page(self, cmd: str, force: bool = False) -> bool:
        out_path = MAN_DIR / f"{cmd}.md"

        if cmd in _COMMAND_META:
            synopsis, description, options, examples = _COMMAND_META[cmd]
            content = _man_template(cmd, synopsis, description, options, examples)
            return self._write_doc(out_path, content, force)

        llm_text = _llm_generate(
            f"""Write a Unix man page for the Terminal Depths game command '{cmd}'.
Include: NAME (one-line summary), SYNOPSIS, DESCRIPTION (2-3 paragraphs, cyberpunk flavour),
OPTIONS (list common flags), EXAMPLES (3 examples).
Format as markdown with ## headings. Keep it under 300 words.""",
            max_tokens=350,
        )
        if llm_text:
            content = f"# {cmd.upper()}(1) — Terminal Depths Man Page\n\n{llm_text}\n\n---\n*Generated {time.strftime('%Y-%m-%d')}*\n"
        else:
            content = _man_template(
                cmd,
                f"Terminal Depths built-in command",
                f"The `{cmd}` command provides functionality within the Terminal Depths hacking simulation.",
                ["Run `help {cmd}` in-game for current options."],
                [f"{cmd}", f"help {cmd}"],
            )
        return self._write_doc(out_path, content, force)

    def generate_lore_page(self, agent_id: str, agent_data: dict, force: bool = False) -> bool:
        out_path = LORE_DIR / f"{agent_id}.md"
        name = agent_data.get("name", agent_id.upper())
        faction = agent_data.get("faction", "UNKNOWN")
        role = agent_data.get("role", "Agent")

        llm_text = _llm_generate(
            f"""Write a 150-word in-universe lore entry for the character '{name}' in Terminal Depths.
Faction: {faction}. Role: {role}.
Write in cyberpunk noir style — terse, mysterious, revealing a partial backstory.
Do NOT use bullet points. Write flowing prose. Stay in-universe.""",
            max_tokens=200,
        )
        lore = llm_text or f"{name} operates within the {faction} power structure. Their motivations remain classified."
        content = _lore_template(agent_id, name, faction, role, lore)
        return self._write_doc(out_path, content, force)

    def generate_system_doc(self, system_name: str, description: str, force: bool = False) -> bool:
        out_path = DEV_DIR / f"{system_name.lower().replace(' ', '_')}.md"
        llm_text = _llm_generate(
            f"""Write developer documentation for the Terminal Depths system: '{system_name}'.
Overview: {description}
Include: Architecture overview, key files, how to extend it, example usage.
Format as markdown. Technical audience. Under 400 words.""",
            max_tokens=450,
        )
        if not llm_text:
            llm_text = f"# {system_name}\n\n{description}\n\n*Full documentation pending.*\n"
        content = f"# {system_name} — Developer Documentation\n\n{llm_text}\n\n---\n*Generated {time.strftime('%Y-%m-%d')}*\n"
        return self._write_doc(out_path, content, force)

    def audit(self) -> dict:
        results = _get("/api/game/commands")
        all_cmds = results.get("commands", list(_COMMAND_META.keys()))

        missing_man = [c for c in all_cmds if not (MAN_DIR / f"{c}.md").exists()]

        agents_data = _get("/api/game/agents")
        all_agents = [a["id"] for a in agents_data.get("agents", [])]
        missing_lore = [a for a in all_agents if not (LORE_DIR / f"{a}.md").exists()]

        return {
            "commands_total": len(all_cmds),
            "man_pages_exist": len(all_cmds) - len(missing_man),
            "man_pages_missing": missing_man,
            "agents_total": len(all_agents),
            "lore_pages_exist": len(all_agents) - len(missing_lore),
            "lore_pages_missing": missing_lore,
        }

    def run_all(self, force: bool = False):
        log("INFO", "Starting full documentation pass")

        results = _get("/api/game/commands")
        all_cmds = results.get("commands", list(_COMMAND_META.keys()))
        log("INFO", f"Generating man pages for {len(all_cmds)} commands")
        for cmd in all_cmds:
            self.generate_man_page(cmd, force=force)

        agents_data = _get("/api/game/agents")
        all_agents = agents_data.get("agents", [])
        log("INFO", f"Generating lore pages for {len(all_agents)} agents")
        for agent in all_agents:
            self.generate_lore_page(agent["id"], agent, force=force)

        _SYSTEMS = [
            ("Plugin System", "Modular plugin architecture for challenge generation, doc generation, code formatting, and test running. Entry: plugins/manager.py"),
            ("MCP Server", "JSON-RPC 2.0 server providing 12 tools for file system, memory, game commands, and LLM generation. Entry: mcp/server.py"),
            ("Agent Framework", "Python agent ecosystem with orchestrator, implementer, tester, documenter, and content generator. Entry: agents/"),
            ("Trust Matrix", "Tracks trust/respect/fear scores between the player and all 59 agents. Entry: app/game_engine/trust_matrix.py"),
            ("Faction System", "Eight faction reputations with perk unlocks and inter-faction conflicts. Entry: app/game_engine/factions.py"),
            ("CHUG Engine", "Perpetual 7-phase improvement cycle: ASSESS→PLAN→EXECUTE→VERIFY→CONSOLIDATE→DOCUMENT→EXPORT. Entry: scripts/devmentor_improve.py"),
            ("NuSyQ Bridge", "Integration with NuSyQ-Hub ecosystem via chronicle JSONL, quest log, NPC memory, and agent manifest. Entry: nusyq_bridge.py"),
            ("LLM Client", "Multi-backend LLM client supporting Replit AI, Ollama, OpenAI, and stub. Entry: scripts/core/llm_client.py"),
        ]
        log("INFO", f"Generating {len(_SYSTEMS)} system developer docs")
        for name, desc in _SYSTEMS:
            self.generate_system_doc(name, desc, force=force)

        log("OK", "Documentation pass complete",
            generated=self.generated, skipped=self.skipped, errors=self.errors)
        return {"generated": self.generated, "skipped": self.skipped, "errors": self.errors}


def _run_task(task_id: str):
    task_path = BASE_DIR / "tasks" / f"{task_id}.json"
    if not task_path.exists():
        log("ERROR", f"Task not found: {task_id}")
        return
    with open(task_path) as f:
        task = json.load(f)
    log("TASK", f"Executing task: {task.get('title', task_id)}")
    doc = Documenter()
    cmd = task.get("target", "")
    if cmd:
        doc.generate_man_page(cmd, force=True)
    else:
        doc.run_all()
    task["status"] = "done"
    task["result"] = f"generated={doc.generated} skipped={doc.skipped}"
    task["updated_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ")
    with open(task_path, "w") as f:
        json.dump(task, f, indent=2)
    log("OK", "Task complete", task=task_id)


def main():
    ap = argparse.ArgumentParser(description="Documentation generator agent")
    ap.add_argument("--man", metavar="CMD", help="Generate man page for one command")
    ap.add_argument("--lore", metavar="AGENT_ID", help="Generate lore page for one agent")
    ap.add_argument("--audit", action="store_true", help="List missing docs")
    ap.add_argument("--dev", action="store_true", help="Generate developer system docs")
    ap.add_argument("--all", action="store_true", help="Regenerate all docs")
    ap.add_argument("--force", action="store_true", help="Overwrite existing docs")
    ap.add_argument("--task", metavar="TASK_ID", help="Run for orchestrator task")
    args = ap.parse_args()

    if args.task:
        _run_task(args.task)
        return

    doc = Documenter()

    if args.audit:
        report = doc.audit()
        print(json.dumps(report, indent=2))
        return

    if args.man:
        doc.generate_man_page(args.man, force=args.force)
        log("OK", f"Man page generated", path=f"docs/commands/{args.man}.md")
        return

    if args.lore:
        agent_data = _get(f"/api/game/agents")
        found = next((a for a in agent_data.get("agents", []) if a["id"] == args.lore), {"name": args.lore, "faction": "UNKNOWN", "role": "Agent"})
        doc.generate_lore_page(args.lore, found, force=args.force)
        log("OK", f"Lore page generated", path=f"docs/lore/{args.lore}.md")
        return

    if args.dev:
        doc.run_all(force=args.force)
        return

    if args.all:
        doc.run_all(force=True)
        return

    audit = doc.audit()
    missing_man = audit["man_pages_missing"]
    missing_lore = audit["lore_pages_missing"]

    log("INFO", f"Missing man pages: {len(missing_man)}  Missing lore pages: {len(missing_lore)}")

    for cmd in missing_man[:10]:
        doc.generate_man_page(cmd)

    for agent_id in missing_lore[:5]:
        agents_data = _get("/api/game/agents")
        found = next((a for a in agents_data.get("agents", []) if a["id"] == agent_id),
                     {"name": agent_id, "faction": "UNKNOWN", "role": "Agent"})
        doc.generate_lore_page(agent_id, found)

    log("OK", "Documentation run complete",
        generated=doc.generated, skipped=doc.skipped)


if __name__ == "__main__":
    main()
