from collections.abc import Sequence
from typing import Any

class SentenceTransformer:
    def __init__(self, model_name: str) -> None: ...
    def encode(self, sentences: str | Sequence[str], **kwargs: Any) -> list[float]: ...
